/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// SecureMessagesAPIService SecureMessagesAPI service
type SecureMessagesAPIService service

type ApiGetSecureMessageConversationRequest struct {
	ctx context.Context
	ApiService *SecureMessagesAPIService
	connectionToken *string
	uid *string
	conId *string
	conversationId *string
}

// Member&#39;s Connection Key
func (r ApiGetSecureMessageConversationRequest) ConnectionToken(connectionToken string) ApiGetSecureMessageConversationRequest {
	r.connectionToken = &connectionToken
	return r
}

// The unique ID of a mydex member
func (r ApiGetSecureMessageConversationRequest) Uid(uid string) ApiGetSecureMessageConversationRequest {
	r.uid = &uid
	return r
}

// The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID.
func (r ApiGetSecureMessageConversationRequest) ConId(conId string) ApiGetSecureMessageConversationRequest {
	r.conId = &conId
	return r
}

// The specific ID of the conversation that groups messages together
func (r ApiGetSecureMessageConversationRequest) ConversationId(conversationId string) ApiGetSecureMessageConversationRequest {
	r.conversationId = &conversationId
	return r
}

func (r ApiGetSecureMessageConversationRequest) Execute() (*SecureMessageConversationResponse, *http.Response, error) {
	return r.ApiService.GetSecureMessageConversationExecute(r)
}

/*
GetSecureMessageConversation Retrieve all secure messages for a given conversation.

Returns a list of secure messages that form part of a conversation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetSecureMessageConversationRequest
*/
func (a *SecureMessagesAPIService) GetSecureMessageConversation(ctx context.Context) ApiGetSecureMessageConversationRequest {
	return ApiGetSecureMessageConversationRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SecureMessageConversationResponse
func (a *SecureMessagesAPIService) GetSecureMessageConversationExecute(r ApiGetSecureMessageConversationRequest) (*SecureMessageConversationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SecureMessageConversationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecureMessagesAPIService.GetSecureMessageConversation")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/secure-messages/conversation"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.connectionToken == nil {
		return localVarReturnValue, nil, reportError("connectionToken is required and must be specified")
	}
	if r.uid == nil {
		return localVarReturnValue, nil, reportError("uid is required and must be specified")
	}
	if r.conId == nil {
		return localVarReturnValue, nil, reportError("conId is required and must be specified")
	}
	if r.conversationId == nil {
		return localVarReturnValue, nil, reportError("conversationId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "uid", r.uid, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "con_id", r.conId, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "conversation_id", r.conversationId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Connection-Token", r.connectionToken, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v AuthErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostSecureMessageReceiveRequest struct {
	ctx context.Context
	ApiService *SecureMessagesAPIService
	connectionToken *string
	uid *string
	conId *string
	secureMessageReceiveRequest *SecureMessageReceiveRequest
}

// Member&#39;s Connection Key
func (r ApiPostSecureMessageReceiveRequest) ConnectionToken(connectionToken string) ApiPostSecureMessageReceiveRequest {
	r.connectionToken = &connectionToken
	return r
}

// The unique ID of a mydex member
func (r ApiPostSecureMessageReceiveRequest) Uid(uid string) ApiPostSecureMessageReceiveRequest {
	r.uid = &uid
	return r
}

// The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID.
func (r ApiPostSecureMessageReceiveRequest) ConId(conId string) ApiPostSecureMessageReceiveRequest {
	r.conId = &conId
	return r
}

func (r ApiPostSecureMessageReceiveRequest) SecureMessageReceiveRequest(secureMessageReceiveRequest SecureMessageReceiveRequest) ApiPostSecureMessageReceiveRequest {
	r.secureMessageReceiveRequest = &secureMessageReceiveRequest
	return r
}

func (r ApiPostSecureMessageReceiveRequest) Execute() (*CreateResponse, *http.Response, error) {
	return r.ApiService.PostSecureMessageReceiveExecute(r)
}

/*
PostSecureMessageReceive Supports sending a message to the member's PDS.

Creates a new received message in the member's PDS.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPostSecureMessageReceiveRequest
*/
func (a *SecureMessagesAPIService) PostSecureMessageReceive(ctx context.Context) ApiPostSecureMessageReceiveRequest {
	return ApiPostSecureMessageReceiveRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CreateResponse
func (a *SecureMessagesAPIService) PostSecureMessageReceiveExecute(r ApiPostSecureMessageReceiveRequest) (*CreateResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecureMessagesAPIService.PostSecureMessageReceive")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/secure-messages/receive"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.connectionToken == nil {
		return localVarReturnValue, nil, reportError("connectionToken is required and must be specified")
	}
	if r.uid == nil {
		return localVarReturnValue, nil, reportError("uid is required and must be specified")
	}
	if r.conId == nil {
		return localVarReturnValue, nil, reportError("conId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "uid", r.uid, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "con_id", r.conId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Connection-Token", r.connectionToken, "simple", "")
	// body params
	localVarPostBody = r.secureMessageReceiveRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v AuthErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostSecureMessageSendRequest struct {
	ctx context.Context
	ApiService *SecureMessagesAPIService
	connectionToken *string
	uid *string
	conId *string
	secureMessageSendRequest *SecureMessageSendRequest
}

// Member&#39;s Connection Key
func (r ApiPostSecureMessageSendRequest) ConnectionToken(connectionToken string) ApiPostSecureMessageSendRequest {
	r.connectionToken = &connectionToken
	return r
}

// The unique ID of a mydex member
func (r ApiPostSecureMessageSendRequest) Uid(uid string) ApiPostSecureMessageSendRequest {
	r.uid = &uid
	return r
}

// The connection_id is a shared id between a connection and a member. It is a hyphenated combination of the member UID and the Dedicated Connection NID.
func (r ApiPostSecureMessageSendRequest) ConId(conId string) ApiPostSecureMessageSendRequest {
	r.conId = &conId
	return r
}

func (r ApiPostSecureMessageSendRequest) SecureMessageSendRequest(secureMessageSendRequest SecureMessageSendRequest) ApiPostSecureMessageSendRequest {
	r.secureMessageSendRequest = &secureMessageSendRequest
	return r
}

func (r ApiPostSecureMessageSendRequest) Execute() (*CreateResponse, *http.Response, error) {
	return r.ApiService.PostSecureMessageSendExecute(r)
}

/*
PostSecureMessageSend Supports sending a message from the member's PDS.

Creates a new sent message in the member's PDS.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPostSecureMessageSendRequest
*/
func (a *SecureMessagesAPIService) PostSecureMessageSend(ctx context.Context) ApiPostSecureMessageSendRequest {
	return ApiPostSecureMessageSendRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CreateResponse
func (a *SecureMessagesAPIService) PostSecureMessageSendExecute(r ApiPostSecureMessageSendRequest) (*CreateResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecureMessagesAPIService.PostSecureMessageSend")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/secure-messages/send"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.connectionToken == nil {
		return localVarReturnValue, nil, reportError("connectionToken is required and must be specified")
	}
	if r.uid == nil {
		return localVarReturnValue, nil, reportError("uid is required and must be specified")
	}
	if r.conId == nil {
		return localVarReturnValue, nil, reportError("conId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "uid", r.uid, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "con_id", r.conId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Connection-Token", r.connectionToken, "simple", "")
	// body params
	localVarPostBody = r.secureMessageSendRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v AuthErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
