/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineResponseTimelineInnerOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineResponseTimelineInnerOneOf{}

// TimelineResponseTimelineInnerOneOf Referral item
type TimelineResponseTimelineInnerOneOf struct {
	Id *int32 `json:"id,omitempty"`
	FeatureBlock *string `json:"feature_block,omitempty"`
	FeatureBlockId *string `json:"feature_block_id,omitempty"`
	StartTimestamp *string `json:"start_timestamp,omitempty"`
	ItemTimestamp *int32 `json:"item_timestamp,omitempty"`
	ServiceDescription *string `json:"service_description,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
	ContactName *string `json:"contact_name,omitempty"`
	ContactTitle *string `json:"contact_title,omitempty"`
	Memo *string `json:"memo,omitempty"`
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineResponseTimelineInnerOneOf TimelineResponseTimelineInnerOneOf

// NewTimelineResponseTimelineInnerOneOf instantiates a new TimelineResponseTimelineInnerOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineResponseTimelineInnerOneOf() *TimelineResponseTimelineInnerOneOf {
	this := TimelineResponseTimelineInnerOneOf{}
	return &this
}

// NewTimelineResponseTimelineInnerOneOfWithDefaults instantiates a new TimelineResponseTimelineInnerOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineResponseTimelineInnerOneOfWithDefaults() *TimelineResponseTimelineInnerOneOf {
	this := TimelineResponseTimelineInnerOneOf{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *TimelineResponseTimelineInnerOneOf) SetId(v int32) {
	o.Id = &v
}

// GetFeatureBlock returns the FeatureBlock field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetFeatureBlock() string {
	if o == nil || IsNil(o.FeatureBlock) {
		var ret string
		return ret
	}
	return *o.FeatureBlock
}

// GetFeatureBlockOk returns a tuple with the FeatureBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetFeatureBlockOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlock) {
		return nil, false
	}
	return o.FeatureBlock, true
}

// HasFeatureBlock returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasFeatureBlock() bool {
	if o != nil && !IsNil(o.FeatureBlock) {
		return true
	}

	return false
}

// SetFeatureBlock gets a reference to the given string and assigns it to the FeatureBlock field.
func (o *TimelineResponseTimelineInnerOneOf) SetFeatureBlock(v string) {
	o.FeatureBlock = &v
}

// GetFeatureBlockId returns the FeatureBlockId field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetFeatureBlockId() string {
	if o == nil || IsNil(o.FeatureBlockId) {
		var ret string
		return ret
	}
	return *o.FeatureBlockId
}

// GetFeatureBlockIdOk returns a tuple with the FeatureBlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetFeatureBlockIdOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlockId) {
		return nil, false
	}
	return o.FeatureBlockId, true
}

// HasFeatureBlockId returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasFeatureBlockId() bool {
	if o != nil && !IsNil(o.FeatureBlockId) {
		return true
	}

	return false
}

// SetFeatureBlockId gets a reference to the given string and assigns it to the FeatureBlockId field.
func (o *TimelineResponseTimelineInnerOneOf) SetFeatureBlockId(v string) {
	o.FeatureBlockId = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetStartTimestamp() string {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret string
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetStartTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given string and assigns it to the StartTimestamp field.
func (o *TimelineResponseTimelineInnerOneOf) SetStartTimestamp(v string) {
	o.StartTimestamp = &v
}

// GetItemTimestamp returns the ItemTimestamp field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetItemTimestamp() int32 {
	if o == nil || IsNil(o.ItemTimestamp) {
		var ret int32
		return ret
	}
	return *o.ItemTimestamp
}

// GetItemTimestampOk returns a tuple with the ItemTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetItemTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.ItemTimestamp) {
		return nil, false
	}
	return o.ItemTimestamp, true
}

// HasItemTimestamp returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasItemTimestamp() bool {
	if o != nil && !IsNil(o.ItemTimestamp) {
		return true
	}

	return false
}

// SetItemTimestamp gets a reference to the given int32 and assigns it to the ItemTimestamp field.
func (o *TimelineResponseTimelineInnerOneOf) SetItemTimestamp(v int32) {
	o.ItemTimestamp = &v
}

// GetServiceDescription returns the ServiceDescription field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetServiceDescription() string {
	if o == nil || IsNil(o.ServiceDescription) {
		var ret string
		return ret
	}
	return *o.ServiceDescription
}

// GetServiceDescriptionOk returns a tuple with the ServiceDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetServiceDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceDescription) {
		return nil, false
	}
	return o.ServiceDescription, true
}

// HasServiceDescription returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasServiceDescription() bool {
	if o != nil && !IsNil(o.ServiceDescription) {
		return true
	}

	return false
}

// SetServiceDescription gets a reference to the given string and assigns it to the ServiceDescription field.
func (o *TimelineResponseTimelineInnerOneOf) SetServiceDescription(v string) {
	o.ServiceDescription = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *TimelineResponseTimelineInnerOneOf) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetContactName() string {
	if o == nil || IsNil(o.ContactName) {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetContactNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContactName) {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasContactName() bool {
	if o != nil && !IsNil(o.ContactName) {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *TimelineResponseTimelineInnerOneOf) SetContactName(v string) {
	o.ContactName = &v
}

// GetContactTitle returns the ContactTitle field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetContactTitle() string {
	if o == nil || IsNil(o.ContactTitle) {
		var ret string
		return ret
	}
	return *o.ContactTitle
}

// GetContactTitleOk returns a tuple with the ContactTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetContactTitleOk() (*string, bool) {
	if o == nil || IsNil(o.ContactTitle) {
		return nil, false
	}
	return o.ContactTitle, true
}

// HasContactTitle returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasContactTitle() bool {
	if o != nil && !IsNil(o.ContactTitle) {
		return true
	}

	return false
}

// SetContactTitle gets a reference to the given string and assigns it to the ContactTitle field.
func (o *TimelineResponseTimelineInnerOneOf) SetContactTitle(v string) {
	o.ContactTitle = &v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *TimelineResponseTimelineInnerOneOf) SetMemo(v string) {
	o.Memo = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TimelineResponseTimelineInnerOneOf) SetStatus(v string) {
	o.Status = &v
}

func (o TimelineResponseTimelineInnerOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineResponseTimelineInnerOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FeatureBlock) {
		toSerialize["feature_block"] = o.FeatureBlock
	}
	if !IsNil(o.FeatureBlockId) {
		toSerialize["feature_block_id"] = o.FeatureBlockId
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.ItemTimestamp) {
		toSerialize["item_timestamp"] = o.ItemTimestamp
	}
	if !IsNil(o.ServiceDescription) {
		toSerialize["service_description"] = o.ServiceDescription
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	if !IsNil(o.ContactName) {
		toSerialize["contact_name"] = o.ContactName
	}
	if !IsNil(o.ContactTitle) {
		toSerialize["contact_title"] = o.ContactTitle
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineResponseTimelineInnerOneOf) UnmarshalJSON(data []byte) (err error) {
	varTimelineResponseTimelineInnerOneOf := _TimelineResponseTimelineInnerOneOf{}

	err = json.Unmarshal(data, &varTimelineResponseTimelineInnerOneOf)

	if err != nil {
		return err
	}

	*o = TimelineResponseTimelineInnerOneOf(varTimelineResponseTimelineInnerOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "feature_block")
		delete(additionalProperties, "feature_block_id")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "item_timestamp")
		delete(additionalProperties, "service_description")
		delete(additionalProperties, "service_name")
		delete(additionalProperties, "contact_name")
		delete(additionalProperties, "contact_title")
		delete(additionalProperties, "memo")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineResponseTimelineInnerOneOf struct {
	value *TimelineResponseTimelineInnerOneOf
	isSet bool
}

func (v NullableTimelineResponseTimelineInnerOneOf) Get() *TimelineResponseTimelineInnerOneOf {
	return v.value
}

func (v *NullableTimelineResponseTimelineInnerOneOf) Set(val *TimelineResponseTimelineInnerOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineResponseTimelineInnerOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineResponseTimelineInnerOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineResponseTimelineInnerOneOf(val *TimelineResponseTimelineInnerOneOf) *NullableTimelineResponseTimelineInnerOneOf {
	return &NullableTimelineResponseTimelineInnerOneOf{value: val, isSet: true}
}

func (v NullableTimelineResponseTimelineInnerOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineResponseTimelineInnerOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


