/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the SecureMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureMessage{}

// SecureMessage A single message within a conversation
type SecureMessage struct {
	// Message ID
	Id *string `json:"id,omitempty"`
	// Conversation identifier
	ConversationId *string `json:"conversation_id,omitempty"`
	// Recipient of the message (present on sent messages)
	MessageTo *string `json:"message_to,omitempty"`
	// Sender of the message (present on received messages)
	MessageFrom *string `json:"message_from,omitempty"`
	// Timestamp when message was sent
	TimeSent *string `json:"time_sent,omitempty"`
	// Timestamp when message was received
	TimeReceived *string `json:"time_received,omitempty"`
	// Content of the message
	MessageContent *string `json:"message_content,omitempty"`
	// Message status
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SecureMessage SecureMessage

// NewSecureMessage instantiates a new SecureMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureMessage() *SecureMessage {
	this := SecureMessage{}
	return &this
}

// NewSecureMessageWithDefaults instantiates a new SecureMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureMessageWithDefaults() *SecureMessage {
	this := SecureMessage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SecureMessage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SecureMessage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SecureMessage) SetId(v string) {
	o.Id = &v
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *SecureMessage) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *SecureMessage) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *SecureMessage) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetMessageTo returns the MessageTo field value if set, zero value otherwise.
func (o *SecureMessage) GetMessageTo() string {
	if o == nil || IsNil(o.MessageTo) {
		var ret string
		return ret
	}
	return *o.MessageTo
}

// GetMessageToOk returns a tuple with the MessageTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetMessageToOk() (*string, bool) {
	if o == nil || IsNil(o.MessageTo) {
		return nil, false
	}
	return o.MessageTo, true
}

// HasMessageTo returns a boolean if a field has been set.
func (o *SecureMessage) HasMessageTo() bool {
	if o != nil && !IsNil(o.MessageTo) {
		return true
	}

	return false
}

// SetMessageTo gets a reference to the given string and assigns it to the MessageTo field.
func (o *SecureMessage) SetMessageTo(v string) {
	o.MessageTo = &v
}

// GetMessageFrom returns the MessageFrom field value if set, zero value otherwise.
func (o *SecureMessage) GetMessageFrom() string {
	if o == nil || IsNil(o.MessageFrom) {
		var ret string
		return ret
	}
	return *o.MessageFrom
}

// GetMessageFromOk returns a tuple with the MessageFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetMessageFromOk() (*string, bool) {
	if o == nil || IsNil(o.MessageFrom) {
		return nil, false
	}
	return o.MessageFrom, true
}

// HasMessageFrom returns a boolean if a field has been set.
func (o *SecureMessage) HasMessageFrom() bool {
	if o != nil && !IsNil(o.MessageFrom) {
		return true
	}

	return false
}

// SetMessageFrom gets a reference to the given string and assigns it to the MessageFrom field.
func (o *SecureMessage) SetMessageFrom(v string) {
	o.MessageFrom = &v
}

// GetTimeSent returns the TimeSent field value if set, zero value otherwise.
func (o *SecureMessage) GetTimeSent() string {
	if o == nil || IsNil(o.TimeSent) {
		var ret string
		return ret
	}
	return *o.TimeSent
}

// GetTimeSentOk returns a tuple with the TimeSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetTimeSentOk() (*string, bool) {
	if o == nil || IsNil(o.TimeSent) {
		return nil, false
	}
	return o.TimeSent, true
}

// HasTimeSent returns a boolean if a field has been set.
func (o *SecureMessage) HasTimeSent() bool {
	if o != nil && !IsNil(o.TimeSent) {
		return true
	}

	return false
}

// SetTimeSent gets a reference to the given string and assigns it to the TimeSent field.
func (o *SecureMessage) SetTimeSent(v string) {
	o.TimeSent = &v
}

// GetTimeReceived returns the TimeReceived field value if set, zero value otherwise.
func (o *SecureMessage) GetTimeReceived() string {
	if o == nil || IsNil(o.TimeReceived) {
		var ret string
		return ret
	}
	return *o.TimeReceived
}

// GetTimeReceivedOk returns a tuple with the TimeReceived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetTimeReceivedOk() (*string, bool) {
	if o == nil || IsNil(o.TimeReceived) {
		return nil, false
	}
	return o.TimeReceived, true
}

// HasTimeReceived returns a boolean if a field has been set.
func (o *SecureMessage) HasTimeReceived() bool {
	if o != nil && !IsNil(o.TimeReceived) {
		return true
	}

	return false
}

// SetTimeReceived gets a reference to the given string and assigns it to the TimeReceived field.
func (o *SecureMessage) SetTimeReceived(v string) {
	o.TimeReceived = &v
}

// GetMessageContent returns the MessageContent field value if set, zero value otherwise.
func (o *SecureMessage) GetMessageContent() string {
	if o == nil || IsNil(o.MessageContent) {
		var ret string
		return ret
	}
	return *o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetMessageContentOk() (*string, bool) {
	if o == nil || IsNil(o.MessageContent) {
		return nil, false
	}
	return o.MessageContent, true
}

// HasMessageContent returns a boolean if a field has been set.
func (o *SecureMessage) HasMessageContent() bool {
	if o != nil && !IsNil(o.MessageContent) {
		return true
	}

	return false
}

// SetMessageContent gets a reference to the given string and assigns it to the MessageContent field.
func (o *SecureMessage) SetMessageContent(v string) {
	o.MessageContent = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SecureMessage) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessage) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SecureMessage) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SecureMessage) SetStatus(v string) {
	o.Status = &v
}

func (o SecureMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ConversationId) {
		toSerialize["conversation_id"] = o.ConversationId
	}
	if !IsNil(o.MessageTo) {
		toSerialize["message_to"] = o.MessageTo
	}
	if !IsNil(o.MessageFrom) {
		toSerialize["message_from"] = o.MessageFrom
	}
	if !IsNil(o.TimeSent) {
		toSerialize["time_sent"] = o.TimeSent
	}
	if !IsNil(o.TimeReceived) {
		toSerialize["time_received"] = o.TimeReceived
	}
	if !IsNil(o.MessageContent) {
		toSerialize["message_content"] = o.MessageContent
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureMessage) UnmarshalJSON(data []byte) (err error) {
	varSecureMessage := _SecureMessage{}

	err = json.Unmarshal(data, &varSecureMessage)

	if err != nil {
		return err
	}

	*o = SecureMessage(varSecureMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "conversation_id")
		delete(additionalProperties, "message_to")
		delete(additionalProperties, "message_from")
		delete(additionalProperties, "time_sent")
		delete(additionalProperties, "time_received")
		delete(additionalProperties, "message_content")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureMessage struct {
	value *SecureMessage
	isSet bool
}

func (v NullableSecureMessage) Get() *SecureMessage {
	return v.value
}

func (v *NullableSecureMessage) Set(val *SecureMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureMessage(val *SecureMessage) *NullableSecureMessage {
	return &NullableSecureMessage{value: val, isSet: true}
}

func (v NullableSecureMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


