/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the ReferralSingleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralSingleResponse{}

// ReferralSingleResponse Response containing a single referral (requires query parameter 'id')
type ReferralSingleResponse struct {
	Success *int32 `json:"success,omitempty"`
	Referral *ReferralSingleResponseReferral `json:"referral,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferralSingleResponse ReferralSingleResponse

// NewReferralSingleResponse instantiates a new ReferralSingleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralSingleResponse() *ReferralSingleResponse {
	this := ReferralSingleResponse{}
	return &this
}

// NewReferralSingleResponseWithDefaults instantiates a new ReferralSingleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralSingleResponseWithDefaults() *ReferralSingleResponse {
	this := ReferralSingleResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ReferralSingleResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ReferralSingleResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *ReferralSingleResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetReferral returns the Referral field value if set, zero value otherwise.
func (o *ReferralSingleResponse) GetReferral() ReferralSingleResponseReferral {
	if o == nil || IsNil(o.Referral) {
		var ret ReferralSingleResponseReferral
		return ret
	}
	return *o.Referral
}

// GetReferralOk returns a tuple with the Referral field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponse) GetReferralOk() (*ReferralSingleResponseReferral, bool) {
	if o == nil || IsNil(o.Referral) {
		return nil, false
	}
	return o.Referral, true
}

// HasReferral returns a boolean if a field has been set.
func (o *ReferralSingleResponse) HasReferral() bool {
	if o != nil && !IsNil(o.Referral) {
		return true
	}

	return false
}

// SetReferral gets a reference to the given ReferralSingleResponseReferral and assigns it to the Referral field.
func (o *ReferralSingleResponse) SetReferral(v ReferralSingleResponseReferral) {
	o.Referral = &v
}

func (o ReferralSingleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralSingleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Referral) {
		toSerialize["referral"] = o.Referral
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralSingleResponse) UnmarshalJSON(data []byte) (err error) {
	varReferralSingleResponse := _ReferralSingleResponse{}

	err = json.Unmarshal(data, &varReferralSingleResponse)

	if err != nil {
		return err
	}

	*o = ReferralSingleResponse(varReferralSingleResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "referral")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralSingleResponse struct {
	value *ReferralSingleResponse
	isSet bool
}

func (v NullableReferralSingleResponse) Get() *ReferralSingleResponse {
	return v.value
}

func (v *NullableReferralSingleResponse) Set(val *ReferralSingleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralSingleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralSingleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralSingleResponse(val *ReferralSingleResponse) *NullableReferralSingleResponse {
	return &NullableReferralSingleResponse{value: val, isSet: true}
}

func (v NullableReferralSingleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralSingleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


