/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineSingleItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineSingleItemResponse{}

// TimelineSingleItemResponse Response containing a single timeline item, which can be a referral, secure message, or calendar event
type TimelineSingleItemResponse struct {
	Success *int32 `json:"success,omitempty"`
	TimelineItem *TimelineSingleItemResponseTimelineItem `json:"timeline_item,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineSingleItemResponse TimelineSingleItemResponse

// NewTimelineSingleItemResponse instantiates a new TimelineSingleItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineSingleItemResponse() *TimelineSingleItemResponse {
	this := TimelineSingleItemResponse{}
	return &this
}

// NewTimelineSingleItemResponseWithDefaults instantiates a new TimelineSingleItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineSingleItemResponseWithDefaults() *TimelineSingleItemResponse {
	this := TimelineSingleItemResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *TimelineSingleItemResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineSingleItemResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *TimelineSingleItemResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *TimelineSingleItemResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetTimelineItem returns the TimelineItem field value if set, zero value otherwise.
func (o *TimelineSingleItemResponse) GetTimelineItem() TimelineSingleItemResponseTimelineItem {
	if o == nil || IsNil(o.TimelineItem) {
		var ret TimelineSingleItemResponseTimelineItem
		return ret
	}
	return *o.TimelineItem
}

// GetTimelineItemOk returns a tuple with the TimelineItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineSingleItemResponse) GetTimelineItemOk() (*TimelineSingleItemResponseTimelineItem, bool) {
	if o == nil || IsNil(o.TimelineItem) {
		return nil, false
	}
	return o.TimelineItem, true
}

// HasTimelineItem returns a boolean if a field has been set.
func (o *TimelineSingleItemResponse) HasTimelineItem() bool {
	if o != nil && !IsNil(o.TimelineItem) {
		return true
	}

	return false
}

// SetTimelineItem gets a reference to the given TimelineSingleItemResponseTimelineItem and assigns it to the TimelineItem field.
func (o *TimelineSingleItemResponse) SetTimelineItem(v TimelineSingleItemResponseTimelineItem) {
	o.TimelineItem = &v
}

func (o TimelineSingleItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineSingleItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.TimelineItem) {
		toSerialize["timeline_item"] = o.TimelineItem
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineSingleItemResponse) UnmarshalJSON(data []byte) (err error) {
	varTimelineSingleItemResponse := _TimelineSingleItemResponse{}

	err = json.Unmarshal(data, &varTimelineSingleItemResponse)

	if err != nil {
		return err
	}

	*o = TimelineSingleItemResponse(varTimelineSingleItemResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "timeline_item")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineSingleItemResponse struct {
	value *TimelineSingleItemResponse
	isSet bool
}

func (v NullableTimelineSingleItemResponse) Get() *TimelineSingleItemResponse {
	return v.value
}

func (v *NullableTimelineSingleItemResponse) Set(val *TimelineSingleItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineSingleItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineSingleItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineSingleItemResponse(val *TimelineSingleItemResponse) *NullableTimelineSingleItemResponse {
	return &NullableTimelineSingleItemResponse{value: val, isSet: true}
}

func (v NullableTimelineSingleItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineSingleItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


