/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the AuthErrorResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthErrorResponseError{}

// AuthErrorResponseError struct for AuthErrorResponseError
type AuthErrorResponseError struct {
	Message *string `json:"message,omitempty"`
	Reason *string `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthErrorResponseError AuthErrorResponseError

// NewAuthErrorResponseError instantiates a new AuthErrorResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthErrorResponseError() *AuthErrorResponseError {
	this := AuthErrorResponseError{}
	return &this
}

// NewAuthErrorResponseErrorWithDefaults instantiates a new AuthErrorResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthErrorResponseErrorWithDefaults() *AuthErrorResponseError {
	this := AuthErrorResponseError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AuthErrorResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthErrorResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AuthErrorResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AuthErrorResponseError) SetMessage(v string) {
	o.Message = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AuthErrorResponseError) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthErrorResponseError) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AuthErrorResponseError) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AuthErrorResponseError) SetReason(v string) {
	o.Reason = &v
}

func (o AuthErrorResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthErrorResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthErrorResponseError) UnmarshalJSON(data []byte) (err error) {
	varAuthErrorResponseError := _AuthErrorResponseError{}

	err = json.Unmarshal(data, &varAuthErrorResponseError)

	if err != nil {
		return err
	}

	*o = AuthErrorResponseError(varAuthErrorResponseError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthErrorResponseError struct {
	value *AuthErrorResponseError
	isSet bool
}

func (v NullableAuthErrorResponseError) Get() *AuthErrorResponseError {
	return v.value
}

func (v *NullableAuthErrorResponseError) Set(val *AuthErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthErrorResponseError(val *AuthErrorResponseError) *NullableAuthErrorResponseError {
	return &NullableAuthErrorResponseError{value: val, isSet: true}
}

func (v NullableAuthErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


