/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the CreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateResponse{}

// CreateResponse struct for CreateResponse
type CreateResponse struct {
	// Indicates success
	Success *int32 `json:"success,omitempty"`
	// ID of the newly created record
	LastInsertId *int32 `json:"last_insert_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateResponse CreateResponse

// NewCreateResponse instantiates a new CreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateResponse() *CreateResponse {
	this := CreateResponse{}
	return &this
}

// NewCreateResponseWithDefaults instantiates a new CreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateResponseWithDefaults() *CreateResponse {
	this := CreateResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *CreateResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetLastInsertId returns the LastInsertId field value if set, zero value otherwise.
func (o *CreateResponse) GetLastInsertId() int32 {
	if o == nil || IsNil(o.LastInsertId) {
		var ret int32
		return ret
	}
	return *o.LastInsertId
}

// GetLastInsertIdOk returns a tuple with the LastInsertId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateResponse) GetLastInsertIdOk() (*int32, bool) {
	if o == nil || IsNil(o.LastInsertId) {
		return nil, false
	}
	return o.LastInsertId, true
}

// HasLastInsertId returns a boolean if a field has been set.
func (o *CreateResponse) HasLastInsertId() bool {
	if o != nil && !IsNil(o.LastInsertId) {
		return true
	}

	return false
}

// SetLastInsertId gets a reference to the given int32 and assigns it to the LastInsertId field.
func (o *CreateResponse) SetLastInsertId(v int32) {
	o.LastInsertId = &v
}

func (o CreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.LastInsertId) {
		toSerialize["last_insert_id"] = o.LastInsertId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateResponse := _CreateResponse{}

	err = json.Unmarshal(data, &varCreateResponse)

	if err != nil {
		return err
	}

	*o = CreateResponse(varCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "last_insert_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateResponse struct {
	value *CreateResponse
	isSet bool
}

func (v NullableCreateResponse) Get() *CreateResponse {
	return v.value
}

func (v *NullableCreateResponse) Set(val *CreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateResponse(val *CreateResponse) *NullableCreateResponse {
	return &NullableCreateResponse{value: val, isSet: true}
}

func (v NullableCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


