/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the CalendarEventCommonRequestBodyFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarEventCommonRequestBodyFields{}

// CalendarEventCommonRequestBodyFields Common fields shared across all calendar event types
type CalendarEventCommonRequestBodyFields struct {
	// Title of the event
	Title *string `json:"title,omitempty"`
	// Detailed description of the event
	Description *string `json:"description,omitempty"`
	// Start date and time as Unix timestamp
	StartTimestamp *int64 `json:"start_timestamp,omitempty"`
	// End date and time as Unix timestamp
	EndTimestamp *int64 `json:"end_timestamp,omitempty"`
	// Status of the event
	Status *string `json:"status,omitempty"`
	// Creator of the event
	Organiser *string `json:"organiser,omitempty"`
	// Person attending the event
	Attendee *string `json:"attendee,omitempty"`
	// Event location
	Location *string `json:"location,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CalendarEventCommonRequestBodyFields CalendarEventCommonRequestBodyFields

// NewCalendarEventCommonRequestBodyFields instantiates a new CalendarEventCommonRequestBodyFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarEventCommonRequestBodyFields() *CalendarEventCommonRequestBodyFields {
	this := CalendarEventCommonRequestBodyFields{}
	var status string = "TENTATIVE"
	this.Status = &status
	return &this
}

// NewCalendarEventCommonRequestBodyFieldsWithDefaults instantiates a new CalendarEventCommonRequestBodyFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarEventCommonRequestBodyFieldsWithDefaults() *CalendarEventCommonRequestBodyFields {
	this := CalendarEventCommonRequestBodyFields{}
	var status string = "TENTATIVE"
	this.Status = &status
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CalendarEventCommonRequestBodyFields) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CalendarEventCommonRequestBodyFields) SetDescription(v string) {
	o.Description = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetStartTimestamp() int64 {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret int64
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetStartTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given int64 and assigns it to the StartTimestamp field.
func (o *CalendarEventCommonRequestBodyFields) SetStartTimestamp(v int64) {
	o.StartTimestamp = &v
}

// GetEndTimestamp returns the EndTimestamp field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetEndTimestamp() int64 {
	if o == nil || IsNil(o.EndTimestamp) {
		var ret int64
		return ret
	}
	return *o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetEndTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTimestamp) {
		return nil, false
	}
	return o.EndTimestamp, true
}

// HasEndTimestamp returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasEndTimestamp() bool {
	if o != nil && !IsNil(o.EndTimestamp) {
		return true
	}

	return false
}

// SetEndTimestamp gets a reference to the given int64 and assigns it to the EndTimestamp field.
func (o *CalendarEventCommonRequestBodyFields) SetEndTimestamp(v int64) {
	o.EndTimestamp = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CalendarEventCommonRequestBodyFields) SetStatus(v string) {
	o.Status = &v
}

// GetOrganiser returns the Organiser field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetOrganiser() string {
	if o == nil || IsNil(o.Organiser) {
		var ret string
		return ret
	}
	return *o.Organiser
}

// GetOrganiserOk returns a tuple with the Organiser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetOrganiserOk() (*string, bool) {
	if o == nil || IsNil(o.Organiser) {
		return nil, false
	}
	return o.Organiser, true
}

// HasOrganiser returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasOrganiser() bool {
	if o != nil && !IsNil(o.Organiser) {
		return true
	}

	return false
}

// SetOrganiser gets a reference to the given string and assigns it to the Organiser field.
func (o *CalendarEventCommonRequestBodyFields) SetOrganiser(v string) {
	o.Organiser = &v
}

// GetAttendee returns the Attendee field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetAttendee() string {
	if o == nil || IsNil(o.Attendee) {
		var ret string
		return ret
	}
	return *o.Attendee
}

// GetAttendeeOk returns a tuple with the Attendee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetAttendeeOk() (*string, bool) {
	if o == nil || IsNil(o.Attendee) {
		return nil, false
	}
	return o.Attendee, true
}

// HasAttendee returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasAttendee() bool {
	if o != nil && !IsNil(o.Attendee) {
		return true
	}

	return false
}

// SetAttendee gets a reference to the given string and assigns it to the Attendee field.
func (o *CalendarEventCommonRequestBodyFields) SetAttendee(v string) {
	o.Attendee = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *CalendarEventCommonRequestBodyFields) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCommonRequestBodyFields) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *CalendarEventCommonRequestBodyFields) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *CalendarEventCommonRequestBodyFields) SetLocation(v string) {
	o.Location = &v
}

func (o CalendarEventCommonRequestBodyFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarEventCommonRequestBodyFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.EndTimestamp) {
		toSerialize["end_timestamp"] = o.EndTimestamp
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Organiser) {
		toSerialize["organiser"] = o.Organiser
	}
	if !IsNil(o.Attendee) {
		toSerialize["attendee"] = o.Attendee
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CalendarEventCommonRequestBodyFields) UnmarshalJSON(data []byte) (err error) {
	varCalendarEventCommonRequestBodyFields := _CalendarEventCommonRequestBodyFields{}

	err = json.Unmarshal(data, &varCalendarEventCommonRequestBodyFields)

	if err != nil {
		return err
	}

	*o = CalendarEventCommonRequestBodyFields(varCalendarEventCommonRequestBodyFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "end_timestamp")
		delete(additionalProperties, "status")
		delete(additionalProperties, "organiser")
		delete(additionalProperties, "attendee")
		delete(additionalProperties, "location")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCalendarEventCommonRequestBodyFields struct {
	value *CalendarEventCommonRequestBodyFields
	isSet bool
}

func (v NullableCalendarEventCommonRequestBodyFields) Get() *CalendarEventCommonRequestBodyFields {
	return v.value
}

func (v *NullableCalendarEventCommonRequestBodyFields) Set(val *CalendarEventCommonRequestBodyFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarEventCommonRequestBodyFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarEventCommonRequestBodyFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarEventCommonRequestBodyFields(val *CalendarEventCommonRequestBodyFields) *NullableCalendarEventCommonRequestBodyFields {
	return &NullableCalendarEventCommonRequestBodyFields{value: val, isSet: true}
}

func (v NullableCalendarEventCommonRequestBodyFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarEventCommonRequestBodyFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


