/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TimelineSingleItemResponseTimelineItem - The timeline item, which can be one of multiple types, returned as an object
type TimelineSingleItemResponseTimelineItem struct {
	TimelineItemCalendarEvent *TimelineItemCalendarEvent
	TimelineItemReferral *TimelineItemReferral
	TimelineItemSecureMessage *TimelineItemSecureMessage
}

// TimelineItemCalendarEventAsTimelineSingleItemResponseTimelineItem is a convenience function that returns TimelineItemCalendarEvent wrapped in TimelineSingleItemResponseTimelineItem
func TimelineItemCalendarEventAsTimelineSingleItemResponseTimelineItem(v *TimelineItemCalendarEvent) TimelineSingleItemResponseTimelineItem {
	return TimelineSingleItemResponseTimelineItem{
		TimelineItemCalendarEvent: v,
	}
}

// TimelineItemReferralAsTimelineSingleItemResponseTimelineItem is a convenience function that returns TimelineItemReferral wrapped in TimelineSingleItemResponseTimelineItem
func TimelineItemReferralAsTimelineSingleItemResponseTimelineItem(v *TimelineItemReferral) TimelineSingleItemResponseTimelineItem {
	return TimelineSingleItemResponseTimelineItem{
		TimelineItemReferral: v,
	}
}

// TimelineItemSecureMessageAsTimelineSingleItemResponseTimelineItem is a convenience function that returns TimelineItemSecureMessage wrapped in TimelineSingleItemResponseTimelineItem
func TimelineItemSecureMessageAsTimelineSingleItemResponseTimelineItem(v *TimelineItemSecureMessage) TimelineSingleItemResponseTimelineItem {
	return TimelineSingleItemResponseTimelineItem{
		TimelineItemSecureMessage: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TimelineSingleItemResponseTimelineItem) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TimelineItemCalendarEvent
	err = newStrictDecoder(data).Decode(&dst.TimelineItemCalendarEvent)
	if err == nil {
		jsonTimelineItemCalendarEvent, _ := json.Marshal(dst.TimelineItemCalendarEvent)
		if string(jsonTimelineItemCalendarEvent) == "{}" { // empty struct
			dst.TimelineItemCalendarEvent = nil
		} else {
			if err = validator.Validate(dst.TimelineItemCalendarEvent); err != nil {
				dst.TimelineItemCalendarEvent = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineItemCalendarEvent = nil
	}

	// try to unmarshal data into TimelineItemReferral
	err = newStrictDecoder(data).Decode(&dst.TimelineItemReferral)
	if err == nil {
		jsonTimelineItemReferral, _ := json.Marshal(dst.TimelineItemReferral)
		if string(jsonTimelineItemReferral) == "{}" { // empty struct
			dst.TimelineItemReferral = nil
		} else {
			if err = validator.Validate(dst.TimelineItemReferral); err != nil {
				dst.TimelineItemReferral = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineItemReferral = nil
	}

	// try to unmarshal data into TimelineItemSecureMessage
	err = newStrictDecoder(data).Decode(&dst.TimelineItemSecureMessage)
	if err == nil {
		jsonTimelineItemSecureMessage, _ := json.Marshal(dst.TimelineItemSecureMessage)
		if string(jsonTimelineItemSecureMessage) == "{}" { // empty struct
			dst.TimelineItemSecureMessage = nil
		} else {
			if err = validator.Validate(dst.TimelineItemSecureMessage); err != nil {
				dst.TimelineItemSecureMessage = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineItemSecureMessage = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TimelineItemCalendarEvent = nil
		dst.TimelineItemReferral = nil
		dst.TimelineItemSecureMessage = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TimelineSingleItemResponseTimelineItem)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TimelineSingleItemResponseTimelineItem)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TimelineSingleItemResponseTimelineItem) MarshalJSON() ([]byte, error) {
	if src.TimelineItemCalendarEvent != nil {
		return json.Marshal(&src.TimelineItemCalendarEvent)
	}

	if src.TimelineItemReferral != nil {
		return json.Marshal(&src.TimelineItemReferral)
	}

	if src.TimelineItemSecureMessage != nil {
		return json.Marshal(&src.TimelineItemSecureMessage)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TimelineSingleItemResponseTimelineItem) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TimelineItemCalendarEvent != nil {
		return obj.TimelineItemCalendarEvent
	}

	if obj.TimelineItemReferral != nil {
		return obj.TimelineItemReferral
	}

	if obj.TimelineItemSecureMessage != nil {
		return obj.TimelineItemSecureMessage
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TimelineSingleItemResponseTimelineItem) GetActualInstanceValue() (interface{}) {
	if obj.TimelineItemCalendarEvent != nil {
		return *obj.TimelineItemCalendarEvent
	}

	if obj.TimelineItemReferral != nil {
		return *obj.TimelineItemReferral
	}

	if obj.TimelineItemSecureMessage != nil {
		return *obj.TimelineItemSecureMessage
	}

	// all schemas are nil
	return nil
}

type NullableTimelineSingleItemResponseTimelineItem struct {
	value *TimelineSingleItemResponseTimelineItem
	isSet bool
}

func (v NullableTimelineSingleItemResponseTimelineItem) Get() *TimelineSingleItemResponseTimelineItem {
	return v.value
}

func (v *NullableTimelineSingleItemResponseTimelineItem) Set(val *TimelineSingleItemResponseTimelineItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineSingleItemResponseTimelineItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineSingleItemResponseTimelineItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineSingleItemResponseTimelineItem(val *TimelineSingleItemResponseTimelineItem) *NullableTimelineSingleItemResponseTimelineItem {
	return &NullableTimelineSingleItemResponseTimelineItem{value: val, isSet: true}
}

func (v NullableTimelineSingleItemResponseTimelineItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineSingleItemResponseTimelineItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


