/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineItemSecureMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineItemSecureMessage{}

// TimelineItemSecureMessage A single timeline item representing a secure message
type TimelineItemSecureMessage struct {
	// Type of feature block this timeline item belongs to
	FeatureBlock *string `json:"feature_block,omitempty"`
	// ID of the feature block
	FeatureBlockId *int32 `json:"feature_block_id,omitempty"`
	// Formatted start timestamp for display
	StartTimestamp *string `json:"start_timestamp,omitempty"`
	// Raw timestamp of the timeline item
	ItemTimestamp *int64 `json:"item_timestamp,omitempty"`
	CreatedTimestamp *int64 `json:"created_timestamp,omitempty"`
	UpdatedTimestamp *int64 `json:"updated_timestamp,omitempty"`
	// Conversation identifier
	ConversationId *string `json:"conversation_id,omitempty"`
	// Timestamp when message was sent
	TimeSent *string `json:"time_sent,omitempty"`
	// Timestamp when message was received
	TimeReceived *string `json:"time_received,omitempty"`
	// Sender of the message (present on received messages)
	MessageFrom *string `json:"message_from,omitempty"`
	// Recipient of the message (present on sent messages)
	MessageTo *string `json:"message_to,omitempty"`
	// Content of the message
	MessageContent *string `json:"message_content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineItemSecureMessage TimelineItemSecureMessage

// NewTimelineItemSecureMessage instantiates a new TimelineItemSecureMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineItemSecureMessage() *TimelineItemSecureMessage {
	this := TimelineItemSecureMessage{}
	return &this
}

// NewTimelineItemSecureMessageWithDefaults instantiates a new TimelineItemSecureMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineItemSecureMessageWithDefaults() *TimelineItemSecureMessage {
	this := TimelineItemSecureMessage{}
	return &this
}

// GetFeatureBlock returns the FeatureBlock field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetFeatureBlock() string {
	if o == nil || IsNil(o.FeatureBlock) {
		var ret string
		return ret
	}
	return *o.FeatureBlock
}

// GetFeatureBlockOk returns a tuple with the FeatureBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetFeatureBlockOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlock) {
		return nil, false
	}
	return o.FeatureBlock, true
}

// HasFeatureBlock returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasFeatureBlock() bool {
	if o != nil && !IsNil(o.FeatureBlock) {
		return true
	}

	return false
}

// SetFeatureBlock gets a reference to the given string and assigns it to the FeatureBlock field.
func (o *TimelineItemSecureMessage) SetFeatureBlock(v string) {
	o.FeatureBlock = &v
}

// GetFeatureBlockId returns the FeatureBlockId field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetFeatureBlockId() int32 {
	if o == nil || IsNil(o.FeatureBlockId) {
		var ret int32
		return ret
	}
	return *o.FeatureBlockId
}

// GetFeatureBlockIdOk returns a tuple with the FeatureBlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetFeatureBlockIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FeatureBlockId) {
		return nil, false
	}
	return o.FeatureBlockId, true
}

// HasFeatureBlockId returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasFeatureBlockId() bool {
	if o != nil && !IsNil(o.FeatureBlockId) {
		return true
	}

	return false
}

// SetFeatureBlockId gets a reference to the given int32 and assigns it to the FeatureBlockId field.
func (o *TimelineItemSecureMessage) SetFeatureBlockId(v int32) {
	o.FeatureBlockId = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetStartTimestamp() string {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret string
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetStartTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given string and assigns it to the StartTimestamp field.
func (o *TimelineItemSecureMessage) SetStartTimestamp(v string) {
	o.StartTimestamp = &v
}

// GetItemTimestamp returns the ItemTimestamp field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetItemTimestamp() int64 {
	if o == nil || IsNil(o.ItemTimestamp) {
		var ret int64
		return ret
	}
	return *o.ItemTimestamp
}

// GetItemTimestampOk returns a tuple with the ItemTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetItemTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.ItemTimestamp) {
		return nil, false
	}
	return o.ItemTimestamp, true
}

// HasItemTimestamp returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasItemTimestamp() bool {
	if o != nil && !IsNil(o.ItemTimestamp) {
		return true
	}

	return false
}

// SetItemTimestamp gets a reference to the given int64 and assigns it to the ItemTimestamp field.
func (o *TimelineItemSecureMessage) SetItemTimestamp(v int64) {
	o.ItemTimestamp = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetCreatedTimestamp() int64 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetCreatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int64 and assigns it to the CreatedTimestamp field.
func (o *TimelineItemSecureMessage) SetCreatedTimestamp(v int64) {
	o.CreatedTimestamp = &v
}

// GetUpdatedTimestamp returns the UpdatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetUpdatedTimestamp() int64 {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.UpdatedTimestamp
}

// GetUpdatedTimestampOk returns a tuple with the UpdatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetUpdatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		return nil, false
	}
	return o.UpdatedTimestamp, true
}

// HasUpdatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasUpdatedTimestamp() bool {
	if o != nil && !IsNil(o.UpdatedTimestamp) {
		return true
	}

	return false
}

// SetUpdatedTimestamp gets a reference to the given int64 and assigns it to the UpdatedTimestamp field.
func (o *TimelineItemSecureMessage) SetUpdatedTimestamp(v int64) {
	o.UpdatedTimestamp = &v
}

// GetConversationId returns the ConversationId field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetConversationId() string {
	if o == nil || IsNil(o.ConversationId) {
		var ret string
		return ret
	}
	return *o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetConversationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConversationId) {
		return nil, false
	}
	return o.ConversationId, true
}

// HasConversationId returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasConversationId() bool {
	if o != nil && !IsNil(o.ConversationId) {
		return true
	}

	return false
}

// SetConversationId gets a reference to the given string and assigns it to the ConversationId field.
func (o *TimelineItemSecureMessage) SetConversationId(v string) {
	o.ConversationId = &v
}

// GetTimeSent returns the TimeSent field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetTimeSent() string {
	if o == nil || IsNil(o.TimeSent) {
		var ret string
		return ret
	}
	return *o.TimeSent
}

// GetTimeSentOk returns a tuple with the TimeSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetTimeSentOk() (*string, bool) {
	if o == nil || IsNil(o.TimeSent) {
		return nil, false
	}
	return o.TimeSent, true
}

// HasTimeSent returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasTimeSent() bool {
	if o != nil && !IsNil(o.TimeSent) {
		return true
	}

	return false
}

// SetTimeSent gets a reference to the given string and assigns it to the TimeSent field.
func (o *TimelineItemSecureMessage) SetTimeSent(v string) {
	o.TimeSent = &v
}

// GetTimeReceived returns the TimeReceived field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetTimeReceived() string {
	if o == nil || IsNil(o.TimeReceived) {
		var ret string
		return ret
	}
	return *o.TimeReceived
}

// GetTimeReceivedOk returns a tuple with the TimeReceived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetTimeReceivedOk() (*string, bool) {
	if o == nil || IsNil(o.TimeReceived) {
		return nil, false
	}
	return o.TimeReceived, true
}

// HasTimeReceived returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasTimeReceived() bool {
	if o != nil && !IsNil(o.TimeReceived) {
		return true
	}

	return false
}

// SetTimeReceived gets a reference to the given string and assigns it to the TimeReceived field.
func (o *TimelineItemSecureMessage) SetTimeReceived(v string) {
	o.TimeReceived = &v
}

// GetMessageFrom returns the MessageFrom field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetMessageFrom() string {
	if o == nil || IsNil(o.MessageFrom) {
		var ret string
		return ret
	}
	return *o.MessageFrom
}

// GetMessageFromOk returns a tuple with the MessageFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetMessageFromOk() (*string, bool) {
	if o == nil || IsNil(o.MessageFrom) {
		return nil, false
	}
	return o.MessageFrom, true
}

// HasMessageFrom returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasMessageFrom() bool {
	if o != nil && !IsNil(o.MessageFrom) {
		return true
	}

	return false
}

// SetMessageFrom gets a reference to the given string and assigns it to the MessageFrom field.
func (o *TimelineItemSecureMessage) SetMessageFrom(v string) {
	o.MessageFrom = &v
}

// GetMessageTo returns the MessageTo field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetMessageTo() string {
	if o == nil || IsNil(o.MessageTo) {
		var ret string
		return ret
	}
	return *o.MessageTo
}

// GetMessageToOk returns a tuple with the MessageTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetMessageToOk() (*string, bool) {
	if o == nil || IsNil(o.MessageTo) {
		return nil, false
	}
	return o.MessageTo, true
}

// HasMessageTo returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasMessageTo() bool {
	if o != nil && !IsNil(o.MessageTo) {
		return true
	}

	return false
}

// SetMessageTo gets a reference to the given string and assigns it to the MessageTo field.
func (o *TimelineItemSecureMessage) SetMessageTo(v string) {
	o.MessageTo = &v
}

// GetMessageContent returns the MessageContent field value if set, zero value otherwise.
func (o *TimelineItemSecureMessage) GetMessageContent() string {
	if o == nil || IsNil(o.MessageContent) {
		var ret string
		return ret
	}
	return *o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemSecureMessage) GetMessageContentOk() (*string, bool) {
	if o == nil || IsNil(o.MessageContent) {
		return nil, false
	}
	return o.MessageContent, true
}

// HasMessageContent returns a boolean if a field has been set.
func (o *TimelineItemSecureMessage) HasMessageContent() bool {
	if o != nil && !IsNil(o.MessageContent) {
		return true
	}

	return false
}

// SetMessageContent gets a reference to the given string and assigns it to the MessageContent field.
func (o *TimelineItemSecureMessage) SetMessageContent(v string) {
	o.MessageContent = &v
}

func (o TimelineItemSecureMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineItemSecureMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureBlock) {
		toSerialize["feature_block"] = o.FeatureBlock
	}
	if !IsNil(o.FeatureBlockId) {
		toSerialize["feature_block_id"] = o.FeatureBlockId
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.ItemTimestamp) {
		toSerialize["item_timestamp"] = o.ItemTimestamp
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.UpdatedTimestamp) {
		toSerialize["updated_timestamp"] = o.UpdatedTimestamp
	}
	if !IsNil(o.ConversationId) {
		toSerialize["conversation_id"] = o.ConversationId
	}
	if !IsNil(o.TimeSent) {
		toSerialize["time_sent"] = o.TimeSent
	}
	if !IsNil(o.TimeReceived) {
		toSerialize["time_received"] = o.TimeReceived
	}
	if !IsNil(o.MessageFrom) {
		toSerialize["message_from"] = o.MessageFrom
	}
	if !IsNil(o.MessageTo) {
		toSerialize["message_to"] = o.MessageTo
	}
	if !IsNil(o.MessageContent) {
		toSerialize["message_content"] = o.MessageContent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineItemSecureMessage) UnmarshalJSON(data []byte) (err error) {
	varTimelineItemSecureMessage := _TimelineItemSecureMessage{}

	err = json.Unmarshal(data, &varTimelineItemSecureMessage)

	if err != nil {
		return err
	}

	*o = TimelineItemSecureMessage(varTimelineItemSecureMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "feature_block")
		delete(additionalProperties, "feature_block_id")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "item_timestamp")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "updated_timestamp")
		delete(additionalProperties, "conversation_id")
		delete(additionalProperties, "time_sent")
		delete(additionalProperties, "time_received")
		delete(additionalProperties, "message_from")
		delete(additionalProperties, "message_to")
		delete(additionalProperties, "message_content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineItemSecureMessage struct {
	value *TimelineItemSecureMessage
	isSet bool
}

func (v NullableTimelineItemSecureMessage) Get() *TimelineItemSecureMessage {
	return v.value
}

func (v *NullableTimelineItemSecureMessage) Set(val *TimelineItemSecureMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineItemSecureMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineItemSecureMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineItemSecureMessage(val *TimelineItemSecureMessage) *NullableTimelineItemSecureMessage {
	return &NullableTimelineItemSecureMessage{value: val, isSet: true}
}

func (v NullableTimelineItemSecureMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineItemSecureMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


