/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the ReferralSingleResponseReferral type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralSingleResponseReferral{}

// ReferralSingleResponseReferral struct for ReferralSingleResponseReferral
type ReferralSingleResponseReferral struct {
	Id *int32 `json:"id,omitempty"`
	CreatedTimestamp *int64 `json:"created_timestamp,omitempty"`
	ServiceId *int32 `json:"service_id,omitempty"`
	Type *string `json:"type,omitempty"`
	Status *string `json:"status,omitempty"`
	Memo *string `json:"memo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferralSingleResponseReferral ReferralSingleResponseReferral

// NewReferralSingleResponseReferral instantiates a new ReferralSingleResponseReferral object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralSingleResponseReferral() *ReferralSingleResponseReferral {
	this := ReferralSingleResponseReferral{}
	return &this
}

// NewReferralSingleResponseReferralWithDefaults instantiates a new ReferralSingleResponseReferral object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralSingleResponseReferralWithDefaults() *ReferralSingleResponseReferral {
	this := ReferralSingleResponseReferral{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ReferralSingleResponseReferral) SetId(v int32) {
	o.Id = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetCreatedTimestamp() int64 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetCreatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int64 and assigns it to the CreatedTimestamp field.
func (o *ReferralSingleResponseReferral) SetCreatedTimestamp(v int64) {
	o.CreatedTimestamp = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetServiceId() int32 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int32
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetServiceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int32 and assigns it to the ServiceId field.
func (o *ReferralSingleResponseReferral) SetServiceId(v int32) {
	o.ServiceId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReferralSingleResponseReferral) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReferralSingleResponseReferral) SetStatus(v string) {
	o.Status = &v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *ReferralSingleResponseReferral) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralSingleResponseReferral) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *ReferralSingleResponseReferral) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *ReferralSingleResponseReferral) SetMemo(v string) {
	o.Memo = &v
}

func (o ReferralSingleResponseReferral) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralSingleResponseReferral) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralSingleResponseReferral) UnmarshalJSON(data []byte) (err error) {
	varReferralSingleResponseReferral := _ReferralSingleResponseReferral{}

	err = json.Unmarshal(data, &varReferralSingleResponseReferral)

	if err != nil {
		return err
	}

	*o = ReferralSingleResponseReferral(varReferralSingleResponseReferral)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "service_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "status")
		delete(additionalProperties, "memo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralSingleResponseReferral struct {
	value *ReferralSingleResponseReferral
	isSet bool
}

func (v NullableReferralSingleResponseReferral) Get() *ReferralSingleResponseReferral {
	return v.value
}

func (v *NullableReferralSingleResponseReferral) Set(val *ReferralSingleResponseReferral) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralSingleResponseReferral) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralSingleResponseReferral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralSingleResponseReferral(val *ReferralSingleResponseReferral) *NullableReferralSingleResponseReferral {
	return &NullableReferralSingleResponseReferral{value: val, isSet: true}
}

func (v NullableReferralSingleResponseReferral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralSingleResponseReferral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


