/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the ReferralListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralListResponse{}

// ReferralListResponse Response containing a list of referrals
type ReferralListResponse struct {
	Success *int32 `json:"success,omitempty"`
	Referrals []ReferralListResponseReferralsInner `json:"referrals,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferralListResponse ReferralListResponse

// NewReferralListResponse instantiates a new ReferralListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralListResponse() *ReferralListResponse {
	this := ReferralListResponse{}
	return &this
}

// NewReferralListResponseWithDefaults instantiates a new ReferralListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralListResponseWithDefaults() *ReferralListResponse {
	this := ReferralListResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ReferralListResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ReferralListResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *ReferralListResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetReferrals returns the Referrals field value if set, zero value otherwise.
func (o *ReferralListResponse) GetReferrals() []ReferralListResponseReferralsInner {
	if o == nil || IsNil(o.Referrals) {
		var ret []ReferralListResponseReferralsInner
		return ret
	}
	return o.Referrals
}

// GetReferralsOk returns a tuple with the Referrals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponse) GetReferralsOk() ([]ReferralListResponseReferralsInner, bool) {
	if o == nil || IsNil(o.Referrals) {
		return nil, false
	}
	return o.Referrals, true
}

// HasReferrals returns a boolean if a field has been set.
func (o *ReferralListResponse) HasReferrals() bool {
	if o != nil && !IsNil(o.Referrals) {
		return true
	}

	return false
}

// SetReferrals gets a reference to the given []ReferralListResponseReferralsInner and assigns it to the Referrals field.
func (o *ReferralListResponse) SetReferrals(v []ReferralListResponseReferralsInner) {
	o.Referrals = v
}

func (o ReferralListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Referrals) {
		toSerialize["referrals"] = o.Referrals
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralListResponse) UnmarshalJSON(data []byte) (err error) {
	varReferralListResponse := _ReferralListResponse{}

	err = json.Unmarshal(data, &varReferralListResponse)

	if err != nil {
		return err
	}

	*o = ReferralListResponse(varReferralListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "referrals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralListResponse struct {
	value *ReferralListResponse
	isSet bool
}

func (v NullableReferralListResponse) Get() *ReferralListResponse {
	return v.value
}

func (v *NullableReferralListResponse) Set(val *ReferralListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralListResponse(val *ReferralListResponse) *NullableReferralListResponse {
	return &NullableReferralListResponse{value: val, isSet: true}
}

func (v NullableReferralListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


