/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the UpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResponse{}

// UpdateResponse struct for UpdateResponse
type UpdateResponse struct {
	// Indicates success
	Success *int32 `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateResponse UpdateResponse

// NewUpdateResponse instantiates a new UpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResponse() *UpdateResponse {
	this := UpdateResponse{}
	return &this
}

// NewUpdateResponseWithDefaults instantiates a new UpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResponseWithDefaults() *UpdateResponse {
	this := UpdateResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *UpdateResponse) SetSuccess(v int32) {
	o.Success = &v
}

func (o UpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateResponse) UnmarshalJSON(data []byte) (err error) {
	varUpdateResponse := _UpdateResponse{}

	err = json.Unmarshal(data, &varUpdateResponse)

	if err != nil {
		return err
	}

	*o = UpdateResponse(varUpdateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateResponse struct {
	value *UpdateResponse
	isSet bool
}

func (v NullableUpdateResponse) Get() *UpdateResponse {
	return v.value
}

func (v *NullableUpdateResponse) Set(val *UpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResponse(val *UpdateResponse) *NullableUpdateResponse {
	return &NullableUpdateResponse{value: val, isSet: true}
}

func (v NullableUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


