/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureMessageCommonFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureMessageCommonFields{}

// SecureMessageCommonFields struct for SecureMessageCommonFields
type SecureMessageCommonFields struct {
	// Content of the message
	MessageContent string `json:"message_content"`
	// ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context.
	ConversationId string `json:"conversation_id"`
	AdditionalProperties map[string]interface{}
}

type _SecureMessageCommonFields SecureMessageCommonFields

// NewSecureMessageCommonFields instantiates a new SecureMessageCommonFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureMessageCommonFields(messageContent string, conversationId string) *SecureMessageCommonFields {
	this := SecureMessageCommonFields{}
	this.MessageContent = messageContent
	this.ConversationId = conversationId
	return &this
}

// NewSecureMessageCommonFieldsWithDefaults instantiates a new SecureMessageCommonFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureMessageCommonFieldsWithDefaults() *SecureMessageCommonFields {
	this := SecureMessageCommonFields{}
	return &this
}

// GetMessageContent returns the MessageContent field value
func (o *SecureMessageCommonFields) GetMessageContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value
// and a boolean to check if the value has been set.
func (o *SecureMessageCommonFields) GetMessageContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageContent, true
}

// SetMessageContent sets field value
func (o *SecureMessageCommonFields) SetMessageContent(v string) {
	o.MessageContent = v
}

// GetConversationId returns the ConversationId field value
func (o *SecureMessageCommonFields) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *SecureMessageCommonFields) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *SecureMessageCommonFields) SetConversationId(v string) {
	o.ConversationId = v
}

func (o SecureMessageCommonFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureMessageCommonFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message_content"] = o.MessageContent
	toSerialize["conversation_id"] = o.ConversationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureMessageCommonFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message_content",
		"conversation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureMessageCommonFields := _SecureMessageCommonFields{}

	err = json.Unmarshal(data, &varSecureMessageCommonFields)

	if err != nil {
		return err
	}

	*o = SecureMessageCommonFields(varSecureMessageCommonFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message_content")
		delete(additionalProperties, "conversation_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureMessageCommonFields struct {
	value *SecureMessageCommonFields
	isSet bool
}

func (v NullableSecureMessageCommonFields) Get() *SecureMessageCommonFields {
	return v.value
}

func (v *NullableSecureMessageCommonFields) Set(val *SecureMessageCommonFields) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureMessageCommonFields) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureMessageCommonFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureMessageCommonFields(val *SecureMessageCommonFields) *NullableSecureMessageCommonFields {
	return &NullableSecureMessageCommonFields{value: val, isSet: true}
}

func (v NullableSecureMessageCommonFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureMessageCommonFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


