/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TimelineResponseTimelineInner - struct for TimelineResponseTimelineInner
type TimelineResponseTimelineInner struct {
	TimelineResponseTimelineInnerOneOf *TimelineResponseTimelineInnerOneOf
	TimelineResponseTimelineInnerOneOf1 *TimelineResponseTimelineInnerOneOf1
	TimelineResponseTimelineInnerOneOf2 *TimelineResponseTimelineInnerOneOf2
}

// TimelineResponseTimelineInnerOneOfAsTimelineResponseTimelineInner is a convenience function that returns TimelineResponseTimelineInnerOneOf wrapped in TimelineResponseTimelineInner
func TimelineResponseTimelineInnerOneOfAsTimelineResponseTimelineInner(v *TimelineResponseTimelineInnerOneOf) TimelineResponseTimelineInner {
	return TimelineResponseTimelineInner{
		TimelineResponseTimelineInnerOneOf: v,
	}
}

// TimelineResponseTimelineInnerOneOf1AsTimelineResponseTimelineInner is a convenience function that returns TimelineResponseTimelineInnerOneOf1 wrapped in TimelineResponseTimelineInner
func TimelineResponseTimelineInnerOneOf1AsTimelineResponseTimelineInner(v *TimelineResponseTimelineInnerOneOf1) TimelineResponseTimelineInner {
	return TimelineResponseTimelineInner{
		TimelineResponseTimelineInnerOneOf1: v,
	}
}

// TimelineResponseTimelineInnerOneOf2AsTimelineResponseTimelineInner is a convenience function that returns TimelineResponseTimelineInnerOneOf2 wrapped in TimelineResponseTimelineInner
func TimelineResponseTimelineInnerOneOf2AsTimelineResponseTimelineInner(v *TimelineResponseTimelineInnerOneOf2) TimelineResponseTimelineInner {
	return TimelineResponseTimelineInner{
		TimelineResponseTimelineInnerOneOf2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TimelineResponseTimelineInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TimelineResponseTimelineInnerOneOf
	err = newStrictDecoder(data).Decode(&dst.TimelineResponseTimelineInnerOneOf)
	if err == nil {
		jsonTimelineResponseTimelineInnerOneOf, _ := json.Marshal(dst.TimelineResponseTimelineInnerOneOf)
		if string(jsonTimelineResponseTimelineInnerOneOf) == "{}" { // empty struct
			dst.TimelineResponseTimelineInnerOneOf = nil
		} else {
			if err = validator.Validate(dst.TimelineResponseTimelineInnerOneOf); err != nil {
				dst.TimelineResponseTimelineInnerOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineResponseTimelineInnerOneOf = nil
	}

	// try to unmarshal data into TimelineResponseTimelineInnerOneOf1
	err = newStrictDecoder(data).Decode(&dst.TimelineResponseTimelineInnerOneOf1)
	if err == nil {
		jsonTimelineResponseTimelineInnerOneOf1, _ := json.Marshal(dst.TimelineResponseTimelineInnerOneOf1)
		if string(jsonTimelineResponseTimelineInnerOneOf1) == "{}" { // empty struct
			dst.TimelineResponseTimelineInnerOneOf1 = nil
		} else {
			if err = validator.Validate(dst.TimelineResponseTimelineInnerOneOf1); err != nil {
				dst.TimelineResponseTimelineInnerOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineResponseTimelineInnerOneOf1 = nil
	}

	// try to unmarshal data into TimelineResponseTimelineInnerOneOf2
	err = newStrictDecoder(data).Decode(&dst.TimelineResponseTimelineInnerOneOf2)
	if err == nil {
		jsonTimelineResponseTimelineInnerOneOf2, _ := json.Marshal(dst.TimelineResponseTimelineInnerOneOf2)
		if string(jsonTimelineResponseTimelineInnerOneOf2) == "{}" { // empty struct
			dst.TimelineResponseTimelineInnerOneOf2 = nil
		} else {
			if err = validator.Validate(dst.TimelineResponseTimelineInnerOneOf2); err != nil {
				dst.TimelineResponseTimelineInnerOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimelineResponseTimelineInnerOneOf2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TimelineResponseTimelineInnerOneOf = nil
		dst.TimelineResponseTimelineInnerOneOf1 = nil
		dst.TimelineResponseTimelineInnerOneOf2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TimelineResponseTimelineInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TimelineResponseTimelineInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TimelineResponseTimelineInner) MarshalJSON() ([]byte, error) {
	if src.TimelineResponseTimelineInnerOneOf != nil {
		return json.Marshal(&src.TimelineResponseTimelineInnerOneOf)
	}

	if src.TimelineResponseTimelineInnerOneOf1 != nil {
		return json.Marshal(&src.TimelineResponseTimelineInnerOneOf1)
	}

	if src.TimelineResponseTimelineInnerOneOf2 != nil {
		return json.Marshal(&src.TimelineResponseTimelineInnerOneOf2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TimelineResponseTimelineInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TimelineResponseTimelineInnerOneOf != nil {
		return obj.TimelineResponseTimelineInnerOneOf
	}

	if obj.TimelineResponseTimelineInnerOneOf1 != nil {
		return obj.TimelineResponseTimelineInnerOneOf1
	}

	if obj.TimelineResponseTimelineInnerOneOf2 != nil {
		return obj.TimelineResponseTimelineInnerOneOf2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TimelineResponseTimelineInner) GetActualInstanceValue() (interface{}) {
	if obj.TimelineResponseTimelineInnerOneOf != nil {
		return *obj.TimelineResponseTimelineInnerOneOf
	}

	if obj.TimelineResponseTimelineInnerOneOf1 != nil {
		return *obj.TimelineResponseTimelineInnerOneOf1
	}

	if obj.TimelineResponseTimelineInnerOneOf2 != nil {
		return *obj.TimelineResponseTimelineInnerOneOf2
	}

	// all schemas are nil
	return nil
}

type NullableTimelineResponseTimelineInner struct {
	value *TimelineResponseTimelineInner
	isSet bool
}

func (v NullableTimelineResponseTimelineInner) Get() *TimelineResponseTimelineInner {
	return v.value
}

func (v *NullableTimelineResponseTimelineInner) Set(val *TimelineResponseTimelineInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineResponseTimelineInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineResponseTimelineInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineResponseTimelineInner(val *TimelineResponseTimelineInner) *NullableTimelineResponseTimelineInner {
	return &NullableTimelineResponseTimelineInner{value: val, isSet: true}
}

func (v NullableTimelineResponseTimelineInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineResponseTimelineInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


