/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the GetEventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEventsResponse{}

// GetEventsResponse struct for GetEventsResponse
type GetEventsResponse struct {
	Success *int32 `json:"success,omitempty"`
	Events []CalendarEvent `json:"events,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetEventsResponse GetEventsResponse

// NewGetEventsResponse instantiates a new GetEventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEventsResponse() *GetEventsResponse {
	this := GetEventsResponse{}
	return &this
}

// NewGetEventsResponseWithDefaults instantiates a new GetEventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEventsResponseWithDefaults() *GetEventsResponse {
	this := GetEventsResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetEventsResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetEventsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *GetEventsResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GetEventsResponse) GetEvents() []CalendarEvent {
	if o == nil || IsNil(o.Events) {
		var ret []CalendarEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEventsResponse) GetEventsOk() ([]CalendarEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GetEventsResponse) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []CalendarEvent and assigns it to the Events field.
func (o *GetEventsResponse) SetEvents(v []CalendarEvent) {
	o.Events = v
}

func (o GetEventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEventsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetEventsResponse := _GetEventsResponse{}

	err = json.Unmarshal(data, &varGetEventsResponse)

	if err != nil {
		return err
	}

	*o = GetEventsResponse(varGetEventsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEventsResponse struct {
	value *GetEventsResponse
	isSet bool
}

func (v NullableGetEventsResponse) Get() *GetEventsResponse {
	return v.value
}

func (v *NullableGetEventsResponse) Set(val *GetEventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventsResponse(val *GetEventsResponse) *NullableGetEventsResponse {
	return &NullableGetEventsResponse{value: val, isSet: true}
}

func (v NullableGetEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


