/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CalendarAppointmentCreateRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarAppointmentCreateRequestBody{}

// CalendarAppointmentCreateRequestBody Fields for creating a calendar event of type 'Appointment'
type CalendarAppointmentCreateRequestBody struct {
	// Title of the event
	Title string `json:"title"`
	// Detailed description of the event
	Description *string `json:"description,omitempty"`
	// Start date and time as Unix timestamp
	StartTimestamp int64 `json:"start_timestamp"`
	// End date and time as Unix timestamp
	EndTimestamp int64 `json:"end_timestamp"`
	// Status of the event
	Status string `json:"status"`
	// Creator of the event
	Organiser *string `json:"organiser,omitempty"`
	// Person attending the event
	Attendee *string `json:"attendee,omitempty"`
	// Event location
	Location *string `json:"location,omitempty"`
	// The context the appointment belongs to e.g. a referral
	Context string `json:"context"`
	// The id of the specific context record that this appointment relates to e.g. the referral id
	ContextId int32 `json:"context_id"`
	AdditionalProperties map[string]interface{}
}

type _CalendarAppointmentCreateRequestBody CalendarAppointmentCreateRequestBody

// NewCalendarAppointmentCreateRequestBody instantiates a new CalendarAppointmentCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarAppointmentCreateRequestBody(title string, startTimestamp int64, endTimestamp int64, status string, context string, contextId int32) *CalendarAppointmentCreateRequestBody {
	this := CalendarAppointmentCreateRequestBody{}
	this.Title = title
	this.StartTimestamp = startTimestamp
	this.EndTimestamp = endTimestamp
	this.Status = status
	this.Context = context
	this.ContextId = contextId
	return &this
}

// NewCalendarAppointmentCreateRequestBodyWithDefaults instantiates a new CalendarAppointmentCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarAppointmentCreateRequestBodyWithDefaults() *CalendarAppointmentCreateRequestBody {
	this := CalendarAppointmentCreateRequestBody{}
	var status string = "TENTATIVE"
	this.Status = status
	return &this
}

// GetTitle returns the Title field value
func (o *CalendarAppointmentCreateRequestBody) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CalendarAppointmentCreateRequestBody) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CalendarAppointmentCreateRequestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CalendarAppointmentCreateRequestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CalendarAppointmentCreateRequestBody) SetDescription(v string) {
	o.Description = &v
}

// GetStartTimestamp returns the StartTimestamp field value
func (o *CalendarAppointmentCreateRequestBody) GetStartTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetStartTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimestamp, true
}

// SetStartTimestamp sets field value
func (o *CalendarAppointmentCreateRequestBody) SetStartTimestamp(v int64) {
	o.StartTimestamp = v
}

// GetEndTimestamp returns the EndTimestamp field value
func (o *CalendarAppointmentCreateRequestBody) GetEndTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetEndTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTimestamp, true
}

// SetEndTimestamp sets field value
func (o *CalendarAppointmentCreateRequestBody) SetEndTimestamp(v int64) {
	o.EndTimestamp = v
}

// GetStatus returns the Status field value
func (o *CalendarAppointmentCreateRequestBody) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CalendarAppointmentCreateRequestBody) SetStatus(v string) {
	o.Status = v
}

// GetOrganiser returns the Organiser field value if set, zero value otherwise.
func (o *CalendarAppointmentCreateRequestBody) GetOrganiser() string {
	if o == nil || IsNil(o.Organiser) {
		var ret string
		return ret
	}
	return *o.Organiser
}

// GetOrganiserOk returns a tuple with the Organiser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetOrganiserOk() (*string, bool) {
	if o == nil || IsNil(o.Organiser) {
		return nil, false
	}
	return o.Organiser, true
}

// HasOrganiser returns a boolean if a field has been set.
func (o *CalendarAppointmentCreateRequestBody) HasOrganiser() bool {
	if o != nil && !IsNil(o.Organiser) {
		return true
	}

	return false
}

// SetOrganiser gets a reference to the given string and assigns it to the Organiser field.
func (o *CalendarAppointmentCreateRequestBody) SetOrganiser(v string) {
	o.Organiser = &v
}

// GetAttendee returns the Attendee field value if set, zero value otherwise.
func (o *CalendarAppointmentCreateRequestBody) GetAttendee() string {
	if o == nil || IsNil(o.Attendee) {
		var ret string
		return ret
	}
	return *o.Attendee
}

// GetAttendeeOk returns a tuple with the Attendee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetAttendeeOk() (*string, bool) {
	if o == nil || IsNil(o.Attendee) {
		return nil, false
	}
	return o.Attendee, true
}

// HasAttendee returns a boolean if a field has been set.
func (o *CalendarAppointmentCreateRequestBody) HasAttendee() bool {
	if o != nil && !IsNil(o.Attendee) {
		return true
	}

	return false
}

// SetAttendee gets a reference to the given string and assigns it to the Attendee field.
func (o *CalendarAppointmentCreateRequestBody) SetAttendee(v string) {
	o.Attendee = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *CalendarAppointmentCreateRequestBody) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *CalendarAppointmentCreateRequestBody) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *CalendarAppointmentCreateRequestBody) SetLocation(v string) {
	o.Location = &v
}

// GetContext returns the Context field value
func (o *CalendarAppointmentCreateRequestBody) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *CalendarAppointmentCreateRequestBody) SetContext(v string) {
	o.Context = v
}

// GetContextId returns the ContextId field value
func (o *CalendarAppointmentCreateRequestBody) GetContextId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContextId
}

// GetContextIdOk returns a tuple with the ContextId field value
// and a boolean to check if the value has been set.
func (o *CalendarAppointmentCreateRequestBody) GetContextIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextId, true
}

// SetContextId sets field value
func (o *CalendarAppointmentCreateRequestBody) SetContextId(v int32) {
	o.ContextId = v
}

func (o CalendarAppointmentCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarAppointmentCreateRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["start_timestamp"] = o.StartTimestamp
	toSerialize["end_timestamp"] = o.EndTimestamp
	toSerialize["status"] = o.Status
	if !IsNil(o.Organiser) {
		toSerialize["organiser"] = o.Organiser
	}
	if !IsNil(o.Attendee) {
		toSerialize["attendee"] = o.Attendee
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	toSerialize["context"] = o.Context
	toSerialize["context_id"] = o.ContextId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CalendarAppointmentCreateRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"start_timestamp",
		"end_timestamp",
		"status",
		"context",
		"context_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarAppointmentCreateRequestBody := _CalendarAppointmentCreateRequestBody{}

	err = json.Unmarshal(data, &varCalendarAppointmentCreateRequestBody)

	if err != nil {
		return err
	}

	*o = CalendarAppointmentCreateRequestBody(varCalendarAppointmentCreateRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "end_timestamp")
		delete(additionalProperties, "status")
		delete(additionalProperties, "organiser")
		delete(additionalProperties, "attendee")
		delete(additionalProperties, "location")
		delete(additionalProperties, "context")
		delete(additionalProperties, "context_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCalendarAppointmentCreateRequestBody struct {
	value *CalendarAppointmentCreateRequestBody
	isSet bool
}

func (v NullableCalendarAppointmentCreateRequestBody) Get() *CalendarAppointmentCreateRequestBody {
	return v.value
}

func (v *NullableCalendarAppointmentCreateRequestBody) Set(val *CalendarAppointmentCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarAppointmentCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarAppointmentCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarAppointmentCreateRequestBody(val *CalendarAppointmentCreateRequestBody) *NullableCalendarAppointmentCreateRequestBody {
	return &NullableCalendarAppointmentCreateRequestBody{value: val, isSet: true}
}

func (v NullableCalendarAppointmentCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarAppointmentCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


