/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the GetAppointmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppointmentsResponse{}

// GetAppointmentsResponse struct for GetAppointmentsResponse
type GetAppointmentsResponse struct {
	Success *int32 `json:"success,omitempty"`
	Appointments []CalendarEvent `json:"appointments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppointmentsResponse GetAppointmentsResponse

// NewGetAppointmentsResponse instantiates a new GetAppointmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppointmentsResponse() *GetAppointmentsResponse {
	this := GetAppointmentsResponse{}
	return &this
}

// NewGetAppointmentsResponseWithDefaults instantiates a new GetAppointmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppointmentsResponseWithDefaults() *GetAppointmentsResponse {
	this := GetAppointmentsResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetAppointmentsResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppointmentsResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetAppointmentsResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *GetAppointmentsResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetAppointments returns the Appointments field value if set, zero value otherwise.
func (o *GetAppointmentsResponse) GetAppointments() []CalendarEvent {
	if o == nil || IsNil(o.Appointments) {
		var ret []CalendarEvent
		return ret
	}
	return o.Appointments
}

// GetAppointmentsOk returns a tuple with the Appointments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppointmentsResponse) GetAppointmentsOk() ([]CalendarEvent, bool) {
	if o == nil || IsNil(o.Appointments) {
		return nil, false
	}
	return o.Appointments, true
}

// HasAppointments returns a boolean if a field has been set.
func (o *GetAppointmentsResponse) HasAppointments() bool {
	if o != nil && !IsNil(o.Appointments) {
		return true
	}

	return false
}

// SetAppointments gets a reference to the given []CalendarEvent and assigns it to the Appointments field.
func (o *GetAppointmentsResponse) SetAppointments(v []CalendarEvent) {
	o.Appointments = v
}

func (o GetAppointmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppointmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Appointments) {
		toSerialize["appointments"] = o.Appointments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppointmentsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetAppointmentsResponse := _GetAppointmentsResponse{}

	err = json.Unmarshal(data, &varGetAppointmentsResponse)

	if err != nil {
		return err
	}

	*o = GetAppointmentsResponse(varGetAppointmentsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "appointments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppointmentsResponse struct {
	value *GetAppointmentsResponse
	isSet bool
}

func (v NullableGetAppointmentsResponse) Get() *GetAppointmentsResponse {
	return v.value
}

func (v *NullableGetAppointmentsResponse) Set(val *GetAppointmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppointmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppointmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppointmentsResponse(val *GetAppointmentsResponse) *NullableGetAppointmentsResponse {
	return &NullableGetAppointmentsResponse{value: val, isSet: true}
}

func (v NullableGetAppointmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppointmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


