/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CalendarEventCreateRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarEventCreateRequestBody{}

// CalendarEventCreateRequestBody Fields for creating a generic calendar event
type CalendarEventCreateRequestBody struct {
	// Title of the event
	Title string `json:"title"`
	// Detailed description of the event
	Description *string `json:"description,omitempty"`
	// Start date and time as Unix timestamp
	StartTimestamp int64 `json:"start_timestamp"`
	// End date and time as Unix timestamp
	EndTimestamp int64 `json:"end_timestamp"`
	// Status of the event
	Status string `json:"status"`
	// Creator of the event
	Organiser *string `json:"organiser,omitempty"`
	// Person attending the event
	Attendee *string `json:"attendee,omitempty"`
	// Event location
	Location *string `json:"location,omitempty"`
	// Type of event
	Type NullableString `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CalendarEventCreateRequestBody CalendarEventCreateRequestBody

// NewCalendarEventCreateRequestBody instantiates a new CalendarEventCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarEventCreateRequestBody(title string, startTimestamp int64, endTimestamp int64, status string) *CalendarEventCreateRequestBody {
	this := CalendarEventCreateRequestBody{}
	this.Title = title
	this.StartTimestamp = startTimestamp
	this.EndTimestamp = endTimestamp
	this.Status = status
	return &this
}

// NewCalendarEventCreateRequestBodyWithDefaults instantiates a new CalendarEventCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarEventCreateRequestBodyWithDefaults() *CalendarEventCreateRequestBody {
	this := CalendarEventCreateRequestBody{}
	var status string = "TENTATIVE"
	this.Status = status
	return &this
}

// GetTitle returns the Title field value
func (o *CalendarEventCreateRequestBody) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CalendarEventCreateRequestBody) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CalendarEventCreateRequestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CalendarEventCreateRequestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CalendarEventCreateRequestBody) SetDescription(v string) {
	o.Description = &v
}

// GetStartTimestamp returns the StartTimestamp field value
func (o *CalendarEventCreateRequestBody) GetStartTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetStartTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimestamp, true
}

// SetStartTimestamp sets field value
func (o *CalendarEventCreateRequestBody) SetStartTimestamp(v int64) {
	o.StartTimestamp = v
}

// GetEndTimestamp returns the EndTimestamp field value
func (o *CalendarEventCreateRequestBody) GetEndTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetEndTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTimestamp, true
}

// SetEndTimestamp sets field value
func (o *CalendarEventCreateRequestBody) SetEndTimestamp(v int64) {
	o.EndTimestamp = v
}

// GetStatus returns the Status field value
func (o *CalendarEventCreateRequestBody) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CalendarEventCreateRequestBody) SetStatus(v string) {
	o.Status = v
}

// GetOrganiser returns the Organiser field value if set, zero value otherwise.
func (o *CalendarEventCreateRequestBody) GetOrganiser() string {
	if o == nil || IsNil(o.Organiser) {
		var ret string
		return ret
	}
	return *o.Organiser
}

// GetOrganiserOk returns a tuple with the Organiser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetOrganiserOk() (*string, bool) {
	if o == nil || IsNil(o.Organiser) {
		return nil, false
	}
	return o.Organiser, true
}

// HasOrganiser returns a boolean if a field has been set.
func (o *CalendarEventCreateRequestBody) HasOrganiser() bool {
	if o != nil && !IsNil(o.Organiser) {
		return true
	}

	return false
}

// SetOrganiser gets a reference to the given string and assigns it to the Organiser field.
func (o *CalendarEventCreateRequestBody) SetOrganiser(v string) {
	o.Organiser = &v
}

// GetAttendee returns the Attendee field value if set, zero value otherwise.
func (o *CalendarEventCreateRequestBody) GetAttendee() string {
	if o == nil || IsNil(o.Attendee) {
		var ret string
		return ret
	}
	return *o.Attendee
}

// GetAttendeeOk returns a tuple with the Attendee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetAttendeeOk() (*string, bool) {
	if o == nil || IsNil(o.Attendee) {
		return nil, false
	}
	return o.Attendee, true
}

// HasAttendee returns a boolean if a field has been set.
func (o *CalendarEventCreateRequestBody) HasAttendee() bool {
	if o != nil && !IsNil(o.Attendee) {
		return true
	}

	return false
}

// SetAttendee gets a reference to the given string and assigns it to the Attendee field.
func (o *CalendarEventCreateRequestBody) SetAttendee(v string) {
	o.Attendee = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *CalendarEventCreateRequestBody) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventCreateRequestBody) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *CalendarEventCreateRequestBody) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *CalendarEventCreateRequestBody) SetLocation(v string) {
	o.Location = &v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarEventCreateRequestBody) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarEventCreateRequestBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *CalendarEventCreateRequestBody) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *CalendarEventCreateRequestBody) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *CalendarEventCreateRequestBody) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *CalendarEventCreateRequestBody) UnsetType() {
	o.Type.Unset()
}

func (o CalendarEventCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarEventCreateRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["start_timestamp"] = o.StartTimestamp
	toSerialize["end_timestamp"] = o.EndTimestamp
	toSerialize["status"] = o.Status
	if !IsNil(o.Organiser) {
		toSerialize["organiser"] = o.Organiser
	}
	if !IsNil(o.Attendee) {
		toSerialize["attendee"] = o.Attendee
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CalendarEventCreateRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"start_timestamp",
		"end_timestamp",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarEventCreateRequestBody := _CalendarEventCreateRequestBody{}

	err = json.Unmarshal(data, &varCalendarEventCreateRequestBody)

	if err != nil {
		return err
	}

	*o = CalendarEventCreateRequestBody(varCalendarEventCreateRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "end_timestamp")
		delete(additionalProperties, "status")
		delete(additionalProperties, "organiser")
		delete(additionalProperties, "attendee")
		delete(additionalProperties, "location")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCalendarEventCreateRequestBody struct {
	value *CalendarEventCreateRequestBody
	isSet bool
}

func (v NullableCalendarEventCreateRequestBody) Get() *CalendarEventCreateRequestBody {
	return v.value
}

func (v *NullableCalendarEventCreateRequestBody) Set(val *CalendarEventCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarEventCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarEventCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarEventCreateRequestBody(val *CalendarEventCreateRequestBody) *NullableCalendarEventCreateRequestBody {
	return &NullableCalendarEventCreateRequestBody{value: val, isSet: true}
}

func (v NullableCalendarEventCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarEventCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


