/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SelfReferralRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelfReferralRequestBody{}

// SelfReferralRequestBody Fields for creating a self referral
type SelfReferralRequestBody struct {
	// ID of the service being referred to
	ServiceId int32 `json:"service_id"`
	// Background information about the referree
	ReferreeBackground *string `json:"referree_background,omitempty"`
	// Requirements of the referree
	ReferreeRequirements *string `json:"referree_requirements,omitempty"`
	ReferreeAvailability *ReferralCommonRequestBodyFieldsReferreeAvailability `json:"referree_availability,omitempty"`
	// Name of the person making the referral
	ReferrerName *string `json:"referrer_name,omitempty"`
	// Name of the service
	ServiceName *string `json:"service_name,omitempty"`
	// Description of the service
	ServiceDescription *string `json:"service_description,omitempty"`
	// URL of the service
	ServiceUrl *string `json:"service_url,omitempty"`
	// Email address of the service
	ServiceEmail *string `json:"service_email,omitempty"`
	// Contact number for the service
	ContactNumber *string `json:"contact_number,omitempty"`
	// Internal memo or notes
	Memo *string `json:"memo,omitempty"`
	// Start time as a Unix timestamp
	StartTime *int64 `json:"start_time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SelfReferralRequestBody SelfReferralRequestBody

// NewSelfReferralRequestBody instantiates a new SelfReferralRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelfReferralRequestBody(serviceId int32) *SelfReferralRequestBody {
	this := SelfReferralRequestBody{}
	this.ServiceId = serviceId
	return &this
}

// NewSelfReferralRequestBodyWithDefaults instantiates a new SelfReferralRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelfReferralRequestBodyWithDefaults() *SelfReferralRequestBody {
	this := SelfReferralRequestBody{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *SelfReferralRequestBody) GetServiceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *SelfReferralRequestBody) SetServiceId(v int32) {
	o.ServiceId = v
}

// GetReferreeBackground returns the ReferreeBackground field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetReferreeBackground() string {
	if o == nil || IsNil(o.ReferreeBackground) {
		var ret string
		return ret
	}
	return *o.ReferreeBackground
}

// GetReferreeBackgroundOk returns a tuple with the ReferreeBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetReferreeBackgroundOk() (*string, bool) {
	if o == nil || IsNil(o.ReferreeBackground) {
		return nil, false
	}
	return o.ReferreeBackground, true
}

// HasReferreeBackground returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasReferreeBackground() bool {
	if o != nil && !IsNil(o.ReferreeBackground) {
		return true
	}

	return false
}

// SetReferreeBackground gets a reference to the given string and assigns it to the ReferreeBackground field.
func (o *SelfReferralRequestBody) SetReferreeBackground(v string) {
	o.ReferreeBackground = &v
}

// GetReferreeRequirements returns the ReferreeRequirements field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetReferreeRequirements() string {
	if o == nil || IsNil(o.ReferreeRequirements) {
		var ret string
		return ret
	}
	return *o.ReferreeRequirements
}

// GetReferreeRequirementsOk returns a tuple with the ReferreeRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetReferreeRequirementsOk() (*string, bool) {
	if o == nil || IsNil(o.ReferreeRequirements) {
		return nil, false
	}
	return o.ReferreeRequirements, true
}

// HasReferreeRequirements returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasReferreeRequirements() bool {
	if o != nil && !IsNil(o.ReferreeRequirements) {
		return true
	}

	return false
}

// SetReferreeRequirements gets a reference to the given string and assigns it to the ReferreeRequirements field.
func (o *SelfReferralRequestBody) SetReferreeRequirements(v string) {
	o.ReferreeRequirements = &v
}

// GetReferreeAvailability returns the ReferreeAvailability field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetReferreeAvailability() ReferralCommonRequestBodyFieldsReferreeAvailability {
	if o == nil || IsNil(o.ReferreeAvailability) {
		var ret ReferralCommonRequestBodyFieldsReferreeAvailability
		return ret
	}
	return *o.ReferreeAvailability
}

// GetReferreeAvailabilityOk returns a tuple with the ReferreeAvailability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetReferreeAvailabilityOk() (*ReferralCommonRequestBodyFieldsReferreeAvailability, bool) {
	if o == nil || IsNil(o.ReferreeAvailability) {
		return nil, false
	}
	return o.ReferreeAvailability, true
}

// HasReferreeAvailability returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasReferreeAvailability() bool {
	if o != nil && !IsNil(o.ReferreeAvailability) {
		return true
	}

	return false
}

// SetReferreeAvailability gets a reference to the given ReferralCommonRequestBodyFieldsReferreeAvailability and assigns it to the ReferreeAvailability field.
func (o *SelfReferralRequestBody) SetReferreeAvailability(v ReferralCommonRequestBodyFieldsReferreeAvailability) {
	o.ReferreeAvailability = &v
}

// GetReferrerName returns the ReferrerName field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetReferrerName() string {
	if o == nil || IsNil(o.ReferrerName) {
		var ret string
		return ret
	}
	return *o.ReferrerName
}

// GetReferrerNameOk returns a tuple with the ReferrerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetReferrerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReferrerName) {
		return nil, false
	}
	return o.ReferrerName, true
}

// HasReferrerName returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasReferrerName() bool {
	if o != nil && !IsNil(o.ReferrerName) {
		return true
	}

	return false
}

// SetReferrerName gets a reference to the given string and assigns it to the ReferrerName field.
func (o *SelfReferralRequestBody) SetReferrerName(v string) {
	o.ReferrerName = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *SelfReferralRequestBody) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetServiceDescription returns the ServiceDescription field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetServiceDescription() string {
	if o == nil || IsNil(o.ServiceDescription) {
		var ret string
		return ret
	}
	return *o.ServiceDescription
}

// GetServiceDescriptionOk returns a tuple with the ServiceDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetServiceDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceDescription) {
		return nil, false
	}
	return o.ServiceDescription, true
}

// HasServiceDescription returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasServiceDescription() bool {
	if o != nil && !IsNil(o.ServiceDescription) {
		return true
	}

	return false
}

// SetServiceDescription gets a reference to the given string and assigns it to the ServiceDescription field.
func (o *SelfReferralRequestBody) SetServiceDescription(v string) {
	o.ServiceDescription = &v
}

// GetServiceUrl returns the ServiceUrl field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetServiceUrl() string {
	if o == nil || IsNil(o.ServiceUrl) {
		var ret string
		return ret
	}
	return *o.ServiceUrl
}

// GetServiceUrlOk returns a tuple with the ServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetServiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUrl) {
		return nil, false
	}
	return o.ServiceUrl, true
}

// HasServiceUrl returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasServiceUrl() bool {
	if o != nil && !IsNil(o.ServiceUrl) {
		return true
	}

	return false
}

// SetServiceUrl gets a reference to the given string and assigns it to the ServiceUrl field.
func (o *SelfReferralRequestBody) SetServiceUrl(v string) {
	o.ServiceUrl = &v
}

// GetServiceEmail returns the ServiceEmail field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetServiceEmail() string {
	if o == nil || IsNil(o.ServiceEmail) {
		var ret string
		return ret
	}
	return *o.ServiceEmail
}

// GetServiceEmailOk returns a tuple with the ServiceEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetServiceEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceEmail) {
		return nil, false
	}
	return o.ServiceEmail, true
}

// HasServiceEmail returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasServiceEmail() bool {
	if o != nil && !IsNil(o.ServiceEmail) {
		return true
	}

	return false
}

// SetServiceEmail gets a reference to the given string and assigns it to the ServiceEmail field.
func (o *SelfReferralRequestBody) SetServiceEmail(v string) {
	o.ServiceEmail = &v
}

// GetContactNumber returns the ContactNumber field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetContactNumber() string {
	if o == nil || IsNil(o.ContactNumber) {
		var ret string
		return ret
	}
	return *o.ContactNumber
}

// GetContactNumberOk returns a tuple with the ContactNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetContactNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ContactNumber) {
		return nil, false
	}
	return o.ContactNumber, true
}

// HasContactNumber returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasContactNumber() bool {
	if o != nil && !IsNil(o.ContactNumber) {
		return true
	}

	return false
}

// SetContactNumber gets a reference to the given string and assigns it to the ContactNumber field.
func (o *SelfReferralRequestBody) SetContactNumber(v string) {
	o.ContactNumber = &v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *SelfReferralRequestBody) SetMemo(v string) {
	o.Memo = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *SelfReferralRequestBody) GetStartTime() int64 {
	if o == nil || IsNil(o.StartTime) {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfReferralRequestBody) GetStartTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *SelfReferralRequestBody) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *SelfReferralRequestBody) SetStartTime(v int64) {
	o.StartTime = &v
}

func (o SelfReferralRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelfReferralRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	if !IsNil(o.ReferreeBackground) {
		toSerialize["referree_background"] = o.ReferreeBackground
	}
	if !IsNil(o.ReferreeRequirements) {
		toSerialize["referree_requirements"] = o.ReferreeRequirements
	}
	if !IsNil(o.ReferreeAvailability) {
		toSerialize["referree_availability"] = o.ReferreeAvailability
	}
	if !IsNil(o.ReferrerName) {
		toSerialize["referrer_name"] = o.ReferrerName
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	if !IsNil(o.ServiceDescription) {
		toSerialize["service_description"] = o.ServiceDescription
	}
	if !IsNil(o.ServiceUrl) {
		toSerialize["service_url"] = o.ServiceUrl
	}
	if !IsNil(o.ServiceEmail) {
		toSerialize["service_email"] = o.ServiceEmail
	}
	if !IsNil(o.ContactNumber) {
		toSerialize["contact_number"] = o.ContactNumber
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SelfReferralRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSelfReferralRequestBody := _SelfReferralRequestBody{}

	err = json.Unmarshal(data, &varSelfReferralRequestBody)

	if err != nil {
		return err
	}

	*o = SelfReferralRequestBody(varSelfReferralRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "service_id")
		delete(additionalProperties, "referree_background")
		delete(additionalProperties, "referree_requirements")
		delete(additionalProperties, "referree_availability")
		delete(additionalProperties, "referrer_name")
		delete(additionalProperties, "service_name")
		delete(additionalProperties, "service_description")
		delete(additionalProperties, "service_url")
		delete(additionalProperties, "service_email")
		delete(additionalProperties, "contact_number")
		delete(additionalProperties, "memo")
		delete(additionalProperties, "start_time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSelfReferralRequestBody struct {
	value *SelfReferralRequestBody
	isSet bool
}

func (v NullableSelfReferralRequestBody) Get() *SelfReferralRequestBody {
	return v.value
}

func (v *NullableSelfReferralRequestBody) Set(val *SelfReferralRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSelfReferralRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSelfReferralRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelfReferralRequestBody(val *SelfReferralRequestBody) *NullableSelfReferralRequestBody {
	return &NullableSelfReferralRequestBody{value: val, isSet: true}
}

func (v NullableSelfReferralRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelfReferralRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


