/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineItemReferral type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineItemReferral{}

// TimelineItemReferral A single timeline item representing a referral
type TimelineItemReferral struct {
	// Type of feature block this timeline item belongs to
	FeatureBlock *string `json:"feature_block,omitempty"`
	// ID of the feature block record i.e. the referral id
	FeatureBlockId *int32 `json:"feature_block_id,omitempty"`
	Instance *string `json:"instance,omitempty"`
	// The context within which this record was created i.e. the specific connection
	Source *string `json:"source,omitempty"`
	CreatedTimestamp *int64 `json:"created_timestamp,omitempty"`
	UpdatedTimestamp *int64 `json:"updated_timestamp,omitempty"`
	// The id of the service that the referral relates to
	ServiceId *int32 `json:"service_id,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
	ServiceDescription *string `json:"service_description,omitempty"`
	ServiceUrl *string `json:"service_url,omitempty"`
	ServiceEmail *string `json:"service_email,omitempty"`
	ContactName *string `json:"contact_name,omitempty"`
	ContactTitle *string `json:"contact_title,omitempty"`
	ContactNumber *string `json:"contact_number,omitempty"`
	ReferrerName *string `json:"referrer_name,omitempty"`
	Status *string `json:"status,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	StartTime *int64 `json:"start_time,omitempty"`
	EndTime *int64 `json:"end_time,omitempty"`
	IsProcessed *bool `json:"is_processed,omitempty"`
	CompleteTime *int32 `json:"complete_time,omitempty"`
	Memo *string `json:"memo,omitempty"`
	Duration *string `json:"duration,omitempty"`
	ReferreeBackground *string `json:"referree_background,omitempty"`
	ReferreeRequirements *string `json:"referree_requirements,omitempty"`
	// Availability of the referree in AM/PM slots
	ReferreeAvailability map[string]interface{} `json:"referree_availability,omitempty"`
	Type *string `json:"type,omitempty"`
	StartTimestamp *string `json:"start_timestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineItemReferral TimelineItemReferral

// NewTimelineItemReferral instantiates a new TimelineItemReferral object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineItemReferral() *TimelineItemReferral {
	this := TimelineItemReferral{}
	return &this
}

// NewTimelineItemReferralWithDefaults instantiates a new TimelineItemReferral object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineItemReferralWithDefaults() *TimelineItemReferral {
	this := TimelineItemReferral{}
	return &this
}

// GetFeatureBlock returns the FeatureBlock field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetFeatureBlock() string {
	if o == nil || IsNil(o.FeatureBlock) {
		var ret string
		return ret
	}
	return *o.FeatureBlock
}

// GetFeatureBlockOk returns a tuple with the FeatureBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetFeatureBlockOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlock) {
		return nil, false
	}
	return o.FeatureBlock, true
}

// HasFeatureBlock returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasFeatureBlock() bool {
	if o != nil && !IsNil(o.FeatureBlock) {
		return true
	}

	return false
}

// SetFeatureBlock gets a reference to the given string and assigns it to the FeatureBlock field.
func (o *TimelineItemReferral) SetFeatureBlock(v string) {
	o.FeatureBlock = &v
}

// GetFeatureBlockId returns the FeatureBlockId field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetFeatureBlockId() int32 {
	if o == nil || IsNil(o.FeatureBlockId) {
		var ret int32
		return ret
	}
	return *o.FeatureBlockId
}

// GetFeatureBlockIdOk returns a tuple with the FeatureBlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetFeatureBlockIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FeatureBlockId) {
		return nil, false
	}
	return o.FeatureBlockId, true
}

// HasFeatureBlockId returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasFeatureBlockId() bool {
	if o != nil && !IsNil(o.FeatureBlockId) {
		return true
	}

	return false
}

// SetFeatureBlockId gets a reference to the given int32 and assigns it to the FeatureBlockId field.
func (o *TimelineItemReferral) SetFeatureBlockId(v int32) {
	o.FeatureBlockId = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetInstance() string {
	if o == nil || IsNil(o.Instance) {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *TimelineItemReferral) SetInstance(v string) {
	o.Instance = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *TimelineItemReferral) SetSource(v string) {
	o.Source = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetCreatedTimestamp() int64 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetCreatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int64 and assigns it to the CreatedTimestamp field.
func (o *TimelineItemReferral) SetCreatedTimestamp(v int64) {
	o.CreatedTimestamp = &v
}

// GetUpdatedTimestamp returns the UpdatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetUpdatedTimestamp() int64 {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.UpdatedTimestamp
}

// GetUpdatedTimestampOk returns a tuple with the UpdatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetUpdatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		return nil, false
	}
	return o.UpdatedTimestamp, true
}

// HasUpdatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasUpdatedTimestamp() bool {
	if o != nil && !IsNil(o.UpdatedTimestamp) {
		return true
	}

	return false
}

// SetUpdatedTimestamp gets a reference to the given int64 and assigns it to the UpdatedTimestamp field.
func (o *TimelineItemReferral) SetUpdatedTimestamp(v int64) {
	o.UpdatedTimestamp = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetServiceId() int32 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int32
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetServiceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int32 and assigns it to the ServiceId field.
func (o *TimelineItemReferral) SetServiceId(v int32) {
	o.ServiceId = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *TimelineItemReferral) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetServiceDescription returns the ServiceDescription field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetServiceDescription() string {
	if o == nil || IsNil(o.ServiceDescription) {
		var ret string
		return ret
	}
	return *o.ServiceDescription
}

// GetServiceDescriptionOk returns a tuple with the ServiceDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetServiceDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceDescription) {
		return nil, false
	}
	return o.ServiceDescription, true
}

// HasServiceDescription returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasServiceDescription() bool {
	if o != nil && !IsNil(o.ServiceDescription) {
		return true
	}

	return false
}

// SetServiceDescription gets a reference to the given string and assigns it to the ServiceDescription field.
func (o *TimelineItemReferral) SetServiceDescription(v string) {
	o.ServiceDescription = &v
}

// GetServiceUrl returns the ServiceUrl field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetServiceUrl() string {
	if o == nil || IsNil(o.ServiceUrl) {
		var ret string
		return ret
	}
	return *o.ServiceUrl
}

// GetServiceUrlOk returns a tuple with the ServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetServiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUrl) {
		return nil, false
	}
	return o.ServiceUrl, true
}

// HasServiceUrl returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasServiceUrl() bool {
	if o != nil && !IsNil(o.ServiceUrl) {
		return true
	}

	return false
}

// SetServiceUrl gets a reference to the given string and assigns it to the ServiceUrl field.
func (o *TimelineItemReferral) SetServiceUrl(v string) {
	o.ServiceUrl = &v
}

// GetServiceEmail returns the ServiceEmail field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetServiceEmail() string {
	if o == nil || IsNil(o.ServiceEmail) {
		var ret string
		return ret
	}
	return *o.ServiceEmail
}

// GetServiceEmailOk returns a tuple with the ServiceEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetServiceEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceEmail) {
		return nil, false
	}
	return o.ServiceEmail, true
}

// HasServiceEmail returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasServiceEmail() bool {
	if o != nil && !IsNil(o.ServiceEmail) {
		return true
	}

	return false
}

// SetServiceEmail gets a reference to the given string and assigns it to the ServiceEmail field.
func (o *TimelineItemReferral) SetServiceEmail(v string) {
	o.ServiceEmail = &v
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetContactName() string {
	if o == nil || IsNil(o.ContactName) {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetContactNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContactName) {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasContactName() bool {
	if o != nil && !IsNil(o.ContactName) {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *TimelineItemReferral) SetContactName(v string) {
	o.ContactName = &v
}

// GetContactTitle returns the ContactTitle field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetContactTitle() string {
	if o == nil || IsNil(o.ContactTitle) {
		var ret string
		return ret
	}
	return *o.ContactTitle
}

// GetContactTitleOk returns a tuple with the ContactTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetContactTitleOk() (*string, bool) {
	if o == nil || IsNil(o.ContactTitle) {
		return nil, false
	}
	return o.ContactTitle, true
}

// HasContactTitle returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasContactTitle() bool {
	if o != nil && !IsNil(o.ContactTitle) {
		return true
	}

	return false
}

// SetContactTitle gets a reference to the given string and assigns it to the ContactTitle field.
func (o *TimelineItemReferral) SetContactTitle(v string) {
	o.ContactTitle = &v
}

// GetContactNumber returns the ContactNumber field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetContactNumber() string {
	if o == nil || IsNil(o.ContactNumber) {
		var ret string
		return ret
	}
	return *o.ContactNumber
}

// GetContactNumberOk returns a tuple with the ContactNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetContactNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ContactNumber) {
		return nil, false
	}
	return o.ContactNumber, true
}

// HasContactNumber returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasContactNumber() bool {
	if o != nil && !IsNil(o.ContactNumber) {
		return true
	}

	return false
}

// SetContactNumber gets a reference to the given string and assigns it to the ContactNumber field.
func (o *TimelineItemReferral) SetContactNumber(v string) {
	o.ContactNumber = &v
}

// GetReferrerName returns the ReferrerName field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetReferrerName() string {
	if o == nil || IsNil(o.ReferrerName) {
		var ret string
		return ret
	}
	return *o.ReferrerName
}

// GetReferrerNameOk returns a tuple with the ReferrerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetReferrerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReferrerName) {
		return nil, false
	}
	return o.ReferrerName, true
}

// HasReferrerName returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasReferrerName() bool {
	if o != nil && !IsNil(o.ReferrerName) {
		return true
	}

	return false
}

// SetReferrerName gets a reference to the given string and assigns it to the ReferrerName field.
func (o *TimelineItemReferral) SetReferrerName(v string) {
	o.ReferrerName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TimelineItemReferral) SetStatus(v string) {
	o.Status = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *TimelineItemReferral) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetStartTime() int64 {
	if o == nil || IsNil(o.StartTime) {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetStartTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *TimelineItemReferral) SetStartTime(v int64) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetEndTime() int64 {
	if o == nil || IsNil(o.EndTime) {
		var ret int64
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetEndTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given int64 and assigns it to the EndTime field.
func (o *TimelineItemReferral) SetEndTime(v int64) {
	o.EndTime = &v
}

// GetIsProcessed returns the IsProcessed field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetIsProcessed() bool {
	if o == nil || IsNil(o.IsProcessed) {
		var ret bool
		return ret
	}
	return *o.IsProcessed
}

// GetIsProcessedOk returns a tuple with the IsProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetIsProcessedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsProcessed) {
		return nil, false
	}
	return o.IsProcessed, true
}

// HasIsProcessed returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasIsProcessed() bool {
	if o != nil && !IsNil(o.IsProcessed) {
		return true
	}

	return false
}

// SetIsProcessed gets a reference to the given bool and assigns it to the IsProcessed field.
func (o *TimelineItemReferral) SetIsProcessed(v bool) {
	o.IsProcessed = &v
}

// GetCompleteTime returns the CompleteTime field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetCompleteTime() int32 {
	if o == nil || IsNil(o.CompleteTime) {
		var ret int32
		return ret
	}
	return *o.CompleteTime
}

// GetCompleteTimeOk returns a tuple with the CompleteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetCompleteTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.CompleteTime) {
		return nil, false
	}
	return o.CompleteTime, true
}

// HasCompleteTime returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasCompleteTime() bool {
	if o != nil && !IsNil(o.CompleteTime) {
		return true
	}

	return false
}

// SetCompleteTime gets a reference to the given int32 and assigns it to the CompleteTime field.
func (o *TimelineItemReferral) SetCompleteTime(v int32) {
	o.CompleteTime = &v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *TimelineItemReferral) SetMemo(v string) {
	o.Memo = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *TimelineItemReferral) SetDuration(v string) {
	o.Duration = &v
}

// GetReferreeBackground returns the ReferreeBackground field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetReferreeBackground() string {
	if o == nil || IsNil(o.ReferreeBackground) {
		var ret string
		return ret
	}
	return *o.ReferreeBackground
}

// GetReferreeBackgroundOk returns a tuple with the ReferreeBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetReferreeBackgroundOk() (*string, bool) {
	if o == nil || IsNil(o.ReferreeBackground) {
		return nil, false
	}
	return o.ReferreeBackground, true
}

// HasReferreeBackground returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasReferreeBackground() bool {
	if o != nil && !IsNil(o.ReferreeBackground) {
		return true
	}

	return false
}

// SetReferreeBackground gets a reference to the given string and assigns it to the ReferreeBackground field.
func (o *TimelineItemReferral) SetReferreeBackground(v string) {
	o.ReferreeBackground = &v
}

// GetReferreeRequirements returns the ReferreeRequirements field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetReferreeRequirements() string {
	if o == nil || IsNil(o.ReferreeRequirements) {
		var ret string
		return ret
	}
	return *o.ReferreeRequirements
}

// GetReferreeRequirementsOk returns a tuple with the ReferreeRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetReferreeRequirementsOk() (*string, bool) {
	if o == nil || IsNil(o.ReferreeRequirements) {
		return nil, false
	}
	return o.ReferreeRequirements, true
}

// HasReferreeRequirements returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasReferreeRequirements() bool {
	if o != nil && !IsNil(o.ReferreeRequirements) {
		return true
	}

	return false
}

// SetReferreeRequirements gets a reference to the given string and assigns it to the ReferreeRequirements field.
func (o *TimelineItemReferral) SetReferreeRequirements(v string) {
	o.ReferreeRequirements = &v
}

// GetReferreeAvailability returns the ReferreeAvailability field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetReferreeAvailability() map[string]interface{} {
	if o == nil || IsNil(o.ReferreeAvailability) {
		var ret map[string]interface{}
		return ret
	}
	return o.ReferreeAvailability
}

// GetReferreeAvailabilityOk returns a tuple with the ReferreeAvailability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetReferreeAvailabilityOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ReferreeAvailability) {
		return map[string]interface{}{}, false
	}
	return o.ReferreeAvailability, true
}

// HasReferreeAvailability returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasReferreeAvailability() bool {
	if o != nil && !IsNil(o.ReferreeAvailability) {
		return true
	}

	return false
}

// SetReferreeAvailability gets a reference to the given map[string]interface{} and assigns it to the ReferreeAvailability field.
func (o *TimelineItemReferral) SetReferreeAvailability(v map[string]interface{}) {
	o.ReferreeAvailability = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TimelineItemReferral) SetType(v string) {
	o.Type = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *TimelineItemReferral) GetStartTimestamp() string {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret string
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemReferral) GetStartTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *TimelineItemReferral) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given string and assigns it to the StartTimestamp field.
func (o *TimelineItemReferral) SetStartTimestamp(v string) {
	o.StartTimestamp = &v
}

func (o TimelineItemReferral) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineItemReferral) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureBlock) {
		toSerialize["feature_block"] = o.FeatureBlock
	}
	if !IsNil(o.FeatureBlockId) {
		toSerialize["feature_block_id"] = o.FeatureBlockId
	}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.UpdatedTimestamp) {
		toSerialize["updated_timestamp"] = o.UpdatedTimestamp
	}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	if !IsNil(o.ServiceDescription) {
		toSerialize["service_description"] = o.ServiceDescription
	}
	if !IsNil(o.ServiceUrl) {
		toSerialize["service_url"] = o.ServiceUrl
	}
	if !IsNil(o.ServiceEmail) {
		toSerialize["service_email"] = o.ServiceEmail
	}
	if !IsNil(o.ContactName) {
		toSerialize["contact_name"] = o.ContactName
	}
	if !IsNil(o.ContactTitle) {
		toSerialize["contact_title"] = o.ContactTitle
	}
	if !IsNil(o.ContactNumber) {
		toSerialize["contact_number"] = o.ContactNumber
	}
	if !IsNil(o.ReferrerName) {
		toSerialize["referrer_name"] = o.ReferrerName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["end_time"] = o.EndTime
	}
	if !IsNil(o.IsProcessed) {
		toSerialize["is_processed"] = o.IsProcessed
	}
	if !IsNil(o.CompleteTime) {
		toSerialize["complete_time"] = o.CompleteTime
	}
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.ReferreeBackground) {
		toSerialize["referree_background"] = o.ReferreeBackground
	}
	if !IsNil(o.ReferreeRequirements) {
		toSerialize["referree_requirements"] = o.ReferreeRequirements
	}
	if !IsNil(o.ReferreeAvailability) {
		toSerialize["referree_availability"] = o.ReferreeAvailability
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineItemReferral) UnmarshalJSON(data []byte) (err error) {
	varTimelineItemReferral := _TimelineItemReferral{}

	err = json.Unmarshal(data, &varTimelineItemReferral)

	if err != nil {
		return err
	}

	*o = TimelineItemReferral(varTimelineItemReferral)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "feature_block")
		delete(additionalProperties, "feature_block_id")
		delete(additionalProperties, "instance")
		delete(additionalProperties, "source")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "updated_timestamp")
		delete(additionalProperties, "service_id")
		delete(additionalProperties, "service_name")
		delete(additionalProperties, "service_description")
		delete(additionalProperties, "service_url")
		delete(additionalProperties, "service_email")
		delete(additionalProperties, "contact_name")
		delete(additionalProperties, "contact_title")
		delete(additionalProperties, "contact_number")
		delete(additionalProperties, "referrer_name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "external_id")
		delete(additionalProperties, "start_time")
		delete(additionalProperties, "end_time")
		delete(additionalProperties, "is_processed")
		delete(additionalProperties, "complete_time")
		delete(additionalProperties, "memo")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "referree_background")
		delete(additionalProperties, "referree_requirements")
		delete(additionalProperties, "referree_availability")
		delete(additionalProperties, "type")
		delete(additionalProperties, "start_timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineItemReferral struct {
	value *TimelineItemReferral
	isSet bool
}

func (v NullableTimelineItemReferral) Get() *TimelineItemReferral {
	return v.value
}

func (v *NullableTimelineItemReferral) Set(val *TimelineItemReferral) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineItemReferral) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineItemReferral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineItemReferral(val *TimelineItemReferral) *NullableTimelineItemReferral {
	return &NullableTimelineItemReferral{value: val, isSet: true}
}

func (v NullableTimelineItemReferral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineItemReferral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


