/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineResponse{}

// TimelineResponse Response containing a mixed timeline of calendar events, referrals, and secure messages
type TimelineResponse struct {
	Success *int32 `json:"success,omitempty"`
	// Array of timeline items, which can be calendar events, referrals, or secure messages
	Timeline []TimelineResponseTimelineInner `json:"timeline,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineResponse TimelineResponse

// NewTimelineResponse instantiates a new TimelineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineResponse() *TimelineResponse {
	this := TimelineResponse{}
	return &this
}

// NewTimelineResponseWithDefaults instantiates a new TimelineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineResponseWithDefaults() *TimelineResponse {
	this := TimelineResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *TimelineResponse) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *TimelineResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *TimelineResponse) SetSuccess(v int32) {
	o.Success = &v
}

// GetTimeline returns the Timeline field value if set, zero value otherwise.
func (o *TimelineResponse) GetTimeline() []TimelineResponseTimelineInner {
	if o == nil || IsNil(o.Timeline) {
		var ret []TimelineResponseTimelineInner
		return ret
	}
	return o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponse) GetTimelineOk() ([]TimelineResponseTimelineInner, bool) {
	if o == nil || IsNil(o.Timeline) {
		return nil, false
	}
	return o.Timeline, true
}

// HasTimeline returns a boolean if a field has been set.
func (o *TimelineResponse) HasTimeline() bool {
	if o != nil && !IsNil(o.Timeline) {
		return true
	}

	return false
}

// SetTimeline gets a reference to the given []TimelineResponseTimelineInner and assigns it to the Timeline field.
func (o *TimelineResponse) SetTimeline(v []TimelineResponseTimelineInner) {
	o.Timeline = v
}

func (o TimelineResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Timeline) {
		toSerialize["timeline"] = o.Timeline
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineResponse) UnmarshalJSON(data []byte) (err error) {
	varTimelineResponse := _TimelineResponse{}

	err = json.Unmarshal(data, &varTimelineResponse)

	if err != nil {
		return err
	}

	*o = TimelineResponse(varTimelineResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "timeline")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineResponse struct {
	value *TimelineResponse
	isSet bool
}

func (v NullableTimelineResponse) Get() *TimelineResponse {
	return v.value
}

func (v *NullableTimelineResponse) Set(val *TimelineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineResponse(val *TimelineResponse) *NullableTimelineResponse {
	return &NullableTimelineResponse{value: val, isSet: true}
}

func (v NullableTimelineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


