/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineItemCalendarEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineItemCalendarEvent{}

// TimelineItemCalendarEvent A single timeline item representing a calendar event
type TimelineItemCalendarEvent struct {
	// Type of feature block this timeline item belongs to
	FeatureBlock *string `json:"feature_block,omitempty"`
	// ID of the feature block
	FeatureBlockId *int32 `json:"feature_block_id,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Source *string `json:"source,omitempty"`
	CreatedTimestamp *string `json:"created_timestamp,omitempty"`
	UpdatedTimestamp *string `json:"updated_timestamp,omitempty"`
	ExternalUid NullableString `json:"external_uid,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Description NullableString `json:"description,omitempty"`
	StartTimestamp *string `json:"start_timestamp,omitempty"`
	EndTimestamp *string `json:"end_timestamp,omitempty"`
	Organiser NullableString `json:"organiser,omitempty"`
	Attendee NullableString `json:"attendee,omitempty"`
	Status NullableString `json:"status,omitempty"`
	Location NullableString `json:"location,omitempty"`
	Type NullableString `json:"type,omitempty"`
	Tags NullableString `json:"tags,omitempty"`
	Trigger NullableString `json:"trigger,omitempty"`
	Action NullableString `json:"action,omitempty"`
	ReminderDescription NullableString `json:"reminder_description,omitempty"`
	DurationString *string `json:"duration_string,omitempty"`
	DurationOfEvent *float32 `json:"duration_of_event,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineItemCalendarEvent TimelineItemCalendarEvent

// NewTimelineItemCalendarEvent instantiates a new TimelineItemCalendarEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineItemCalendarEvent() *TimelineItemCalendarEvent {
	this := TimelineItemCalendarEvent{}
	return &this
}

// NewTimelineItemCalendarEventWithDefaults instantiates a new TimelineItemCalendarEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineItemCalendarEventWithDefaults() *TimelineItemCalendarEvent {
	this := TimelineItemCalendarEvent{}
	return &this
}

// GetFeatureBlock returns the FeatureBlock field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetFeatureBlock() string {
	if o == nil || IsNil(o.FeatureBlock) {
		var ret string
		return ret
	}
	return *o.FeatureBlock
}

// GetFeatureBlockOk returns a tuple with the FeatureBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetFeatureBlockOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlock) {
		return nil, false
	}
	return o.FeatureBlock, true
}

// HasFeatureBlock returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasFeatureBlock() bool {
	if o != nil && !IsNil(o.FeatureBlock) {
		return true
	}

	return false
}

// SetFeatureBlock gets a reference to the given string and assigns it to the FeatureBlock field.
func (o *TimelineItemCalendarEvent) SetFeatureBlock(v string) {
	o.FeatureBlock = &v
}

// GetFeatureBlockId returns the FeatureBlockId field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetFeatureBlockId() int32 {
	if o == nil || IsNil(o.FeatureBlockId) {
		var ret int32
		return ret
	}
	return *o.FeatureBlockId
}

// GetFeatureBlockIdOk returns a tuple with the FeatureBlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetFeatureBlockIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FeatureBlockId) {
		return nil, false
	}
	return o.FeatureBlockId, true
}

// HasFeatureBlockId returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasFeatureBlockId() bool {
	if o != nil && !IsNil(o.FeatureBlockId) {
		return true
	}

	return false
}

// SetFeatureBlockId gets a reference to the given int32 and assigns it to the FeatureBlockId field.
func (o *TimelineItemCalendarEvent) SetFeatureBlockId(v int32) {
	o.FeatureBlockId = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetInstance() string {
	if o == nil || IsNil(o.Instance) {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *TimelineItemCalendarEvent) SetInstance(v string) {
	o.Instance = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *TimelineItemCalendarEvent) SetSource(v string) {
	o.Source = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetCreatedTimestamp() string {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret string
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetCreatedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given string and assigns it to the CreatedTimestamp field.
func (o *TimelineItemCalendarEvent) SetCreatedTimestamp(v string) {
	o.CreatedTimestamp = &v
}

// GetUpdatedTimestamp returns the UpdatedTimestamp field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetUpdatedTimestamp() string {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		var ret string
		return ret
	}
	return *o.UpdatedTimestamp
}

// GetUpdatedTimestampOk returns a tuple with the UpdatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetUpdatedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		return nil, false
	}
	return o.UpdatedTimestamp, true
}

// HasUpdatedTimestamp returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasUpdatedTimestamp() bool {
	if o != nil && !IsNil(o.UpdatedTimestamp) {
		return true
	}

	return false
}

// SetUpdatedTimestamp gets a reference to the given string and assigns it to the UpdatedTimestamp field.
func (o *TimelineItemCalendarEvent) SetUpdatedTimestamp(v string) {
	o.UpdatedTimestamp = &v
}

// GetExternalUid returns the ExternalUid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetExternalUid() string {
	if o == nil || IsNil(o.ExternalUid.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalUid.Get()
}

// GetExternalUidOk returns a tuple with the ExternalUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetExternalUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalUid.Get(), o.ExternalUid.IsSet()
}

// HasExternalUid returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasExternalUid() bool {
	if o != nil && o.ExternalUid.IsSet() {
		return true
	}

	return false
}

// SetExternalUid gets a reference to the given NullableString and assigns it to the ExternalUid field.
func (o *TimelineItemCalendarEvent) SetExternalUid(v string) {
	o.ExternalUid.Set(&v)
}
// SetExternalUidNil sets the value for ExternalUid to be an explicit nil
func (o *TimelineItemCalendarEvent) SetExternalUidNil() {
	o.ExternalUid.Set(nil)
}

// UnsetExternalUid ensures that no value is present for ExternalUid, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetExternalUid() {
	o.ExternalUid.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *TimelineItemCalendarEvent) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *TimelineItemCalendarEvent) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetTitle() {
	o.Title.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *TimelineItemCalendarEvent) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *TimelineItemCalendarEvent) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetDescription() {
	o.Description.Unset()
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetStartTimestamp() string {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret string
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetStartTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given string and assigns it to the StartTimestamp field.
func (o *TimelineItemCalendarEvent) SetStartTimestamp(v string) {
	o.StartTimestamp = &v
}

// GetEndTimestamp returns the EndTimestamp field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetEndTimestamp() string {
	if o == nil || IsNil(o.EndTimestamp) {
		var ret string
		return ret
	}
	return *o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetEndTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.EndTimestamp) {
		return nil, false
	}
	return o.EndTimestamp, true
}

// HasEndTimestamp returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasEndTimestamp() bool {
	if o != nil && !IsNil(o.EndTimestamp) {
		return true
	}

	return false
}

// SetEndTimestamp gets a reference to the given string and assigns it to the EndTimestamp field.
func (o *TimelineItemCalendarEvent) SetEndTimestamp(v string) {
	o.EndTimestamp = &v
}

// GetOrganiser returns the Organiser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetOrganiser() string {
	if o == nil || IsNil(o.Organiser.Get()) {
		var ret string
		return ret
	}
	return *o.Organiser.Get()
}

// GetOrganiserOk returns a tuple with the Organiser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetOrganiserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Organiser.Get(), o.Organiser.IsSet()
}

// HasOrganiser returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasOrganiser() bool {
	if o != nil && o.Organiser.IsSet() {
		return true
	}

	return false
}

// SetOrganiser gets a reference to the given NullableString and assigns it to the Organiser field.
func (o *TimelineItemCalendarEvent) SetOrganiser(v string) {
	o.Organiser.Set(&v)
}
// SetOrganiserNil sets the value for Organiser to be an explicit nil
func (o *TimelineItemCalendarEvent) SetOrganiserNil() {
	o.Organiser.Set(nil)
}

// UnsetOrganiser ensures that no value is present for Organiser, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetOrganiser() {
	o.Organiser.Unset()
}

// GetAttendee returns the Attendee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetAttendee() string {
	if o == nil || IsNil(o.Attendee.Get()) {
		var ret string
		return ret
	}
	return *o.Attendee.Get()
}

// GetAttendeeOk returns a tuple with the Attendee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetAttendeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attendee.Get(), o.Attendee.IsSet()
}

// HasAttendee returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasAttendee() bool {
	if o != nil && o.Attendee.IsSet() {
		return true
	}

	return false
}

// SetAttendee gets a reference to the given NullableString and assigns it to the Attendee field.
func (o *TimelineItemCalendarEvent) SetAttendee(v string) {
	o.Attendee.Set(&v)
}
// SetAttendeeNil sets the value for Attendee to be an explicit nil
func (o *TimelineItemCalendarEvent) SetAttendeeNil() {
	o.Attendee.Set(nil)
}

// UnsetAttendee ensures that no value is present for Attendee, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetAttendee() {
	o.Attendee.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *TimelineItemCalendarEvent) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *TimelineItemCalendarEvent) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetStatus() {
	o.Status.Unset()
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetLocation() string {
	if o == nil || IsNil(o.Location.Get()) {
		var ret string
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableString and assigns it to the Location field.
func (o *TimelineItemCalendarEvent) SetLocation(v string) {
	o.Location.Set(&v)
}
// SetLocationNil sets the value for Location to be an explicit nil
func (o *TimelineItemCalendarEvent) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetLocation() {
	o.Location.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *TimelineItemCalendarEvent) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *TimelineItemCalendarEvent) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetType() {
	o.Type.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetTags() string {
	if o == nil || IsNil(o.Tags.Get()) {
		var ret string
		return ret
	}
	return *o.Tags.Get()
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags.Get(), o.Tags.IsSet()
}

// HasTags returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasTags() bool {
	if o != nil && o.Tags.IsSet() {
		return true
	}

	return false
}

// SetTags gets a reference to the given NullableString and assigns it to the Tags field.
func (o *TimelineItemCalendarEvent) SetTags(v string) {
	o.Tags.Set(&v)
}
// SetTagsNil sets the value for Tags to be an explicit nil
func (o *TimelineItemCalendarEvent) SetTagsNil() {
	o.Tags.Set(nil)
}

// UnsetTags ensures that no value is present for Tags, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetTags() {
	o.Tags.Unset()
}

// GetTrigger returns the Trigger field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetTrigger() string {
	if o == nil || IsNil(o.Trigger.Get()) {
		var ret string
		return ret
	}
	return *o.Trigger.Get()
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetTriggerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Trigger.Get(), o.Trigger.IsSet()
}

// HasTrigger returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasTrigger() bool {
	if o != nil && o.Trigger.IsSet() {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given NullableString and assigns it to the Trigger field.
func (o *TimelineItemCalendarEvent) SetTrigger(v string) {
	o.Trigger.Set(&v)
}
// SetTriggerNil sets the value for Trigger to be an explicit nil
func (o *TimelineItemCalendarEvent) SetTriggerNil() {
	o.Trigger.Set(nil)
}

// UnsetTrigger ensures that no value is present for Trigger, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetTrigger() {
	o.Trigger.Unset()
}

// GetAction returns the Action field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetAction() string {
	if o == nil || IsNil(o.Action.Get()) {
		var ret string
		return ret
	}
	return *o.Action.Get()
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Action.Get(), o.Action.IsSet()
}

// HasAction returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasAction() bool {
	if o != nil && o.Action.IsSet() {
		return true
	}

	return false
}

// SetAction gets a reference to the given NullableString and assigns it to the Action field.
func (o *TimelineItemCalendarEvent) SetAction(v string) {
	o.Action.Set(&v)
}
// SetActionNil sets the value for Action to be an explicit nil
func (o *TimelineItemCalendarEvent) SetActionNil() {
	o.Action.Set(nil)
}

// UnsetAction ensures that no value is present for Action, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetAction() {
	o.Action.Unset()
}

// GetReminderDescription returns the ReminderDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimelineItemCalendarEvent) GetReminderDescription() string {
	if o == nil || IsNil(o.ReminderDescription.Get()) {
		var ret string
		return ret
	}
	return *o.ReminderDescription.Get()
}

// GetReminderDescriptionOk returns a tuple with the ReminderDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimelineItemCalendarEvent) GetReminderDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReminderDescription.Get(), o.ReminderDescription.IsSet()
}

// HasReminderDescription returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasReminderDescription() bool {
	if o != nil && o.ReminderDescription.IsSet() {
		return true
	}

	return false
}

// SetReminderDescription gets a reference to the given NullableString and assigns it to the ReminderDescription field.
func (o *TimelineItemCalendarEvent) SetReminderDescription(v string) {
	o.ReminderDescription.Set(&v)
}
// SetReminderDescriptionNil sets the value for ReminderDescription to be an explicit nil
func (o *TimelineItemCalendarEvent) SetReminderDescriptionNil() {
	o.ReminderDescription.Set(nil)
}

// UnsetReminderDescription ensures that no value is present for ReminderDescription, not even an explicit nil
func (o *TimelineItemCalendarEvent) UnsetReminderDescription() {
	o.ReminderDescription.Unset()
}

// GetDurationString returns the DurationString field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetDurationString() string {
	if o == nil || IsNil(o.DurationString) {
		var ret string
		return ret
	}
	return *o.DurationString
}

// GetDurationStringOk returns a tuple with the DurationString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetDurationStringOk() (*string, bool) {
	if o == nil || IsNil(o.DurationString) {
		return nil, false
	}
	return o.DurationString, true
}

// HasDurationString returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasDurationString() bool {
	if o != nil && !IsNil(o.DurationString) {
		return true
	}

	return false
}

// SetDurationString gets a reference to the given string and assigns it to the DurationString field.
func (o *TimelineItemCalendarEvent) SetDurationString(v string) {
	o.DurationString = &v
}

// GetDurationOfEvent returns the DurationOfEvent field value if set, zero value otherwise.
func (o *TimelineItemCalendarEvent) GetDurationOfEvent() float32 {
	if o == nil || IsNil(o.DurationOfEvent) {
		var ret float32
		return ret
	}
	return *o.DurationOfEvent
}

// GetDurationOfEventOk returns a tuple with the DurationOfEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineItemCalendarEvent) GetDurationOfEventOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationOfEvent) {
		return nil, false
	}
	return o.DurationOfEvent, true
}

// HasDurationOfEvent returns a boolean if a field has been set.
func (o *TimelineItemCalendarEvent) HasDurationOfEvent() bool {
	if o != nil && !IsNil(o.DurationOfEvent) {
		return true
	}

	return false
}

// SetDurationOfEvent gets a reference to the given float32 and assigns it to the DurationOfEvent field.
func (o *TimelineItemCalendarEvent) SetDurationOfEvent(v float32) {
	o.DurationOfEvent = &v
}

func (o TimelineItemCalendarEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineItemCalendarEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureBlock) {
		toSerialize["feature_block"] = o.FeatureBlock
	}
	if !IsNil(o.FeatureBlockId) {
		toSerialize["feature_block_id"] = o.FeatureBlockId
	}
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.UpdatedTimestamp) {
		toSerialize["updated_timestamp"] = o.UpdatedTimestamp
	}
	if o.ExternalUid.IsSet() {
		toSerialize["external_uid"] = o.ExternalUid.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.EndTimestamp) {
		toSerialize["end_timestamp"] = o.EndTimestamp
	}
	if o.Organiser.IsSet() {
		toSerialize["organiser"] = o.Organiser.Get()
	}
	if o.Attendee.IsSet() {
		toSerialize["attendee"] = o.Attendee.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.Tags.IsSet() {
		toSerialize["tags"] = o.Tags.Get()
	}
	if o.Trigger.IsSet() {
		toSerialize["trigger"] = o.Trigger.Get()
	}
	if o.Action.IsSet() {
		toSerialize["action"] = o.Action.Get()
	}
	if o.ReminderDescription.IsSet() {
		toSerialize["reminder_description"] = o.ReminderDescription.Get()
	}
	if !IsNil(o.DurationString) {
		toSerialize["duration_string"] = o.DurationString
	}
	if !IsNil(o.DurationOfEvent) {
		toSerialize["duration_of_event"] = o.DurationOfEvent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineItemCalendarEvent) UnmarshalJSON(data []byte) (err error) {
	varTimelineItemCalendarEvent := _TimelineItemCalendarEvent{}

	err = json.Unmarshal(data, &varTimelineItemCalendarEvent)

	if err != nil {
		return err
	}

	*o = TimelineItemCalendarEvent(varTimelineItemCalendarEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "feature_block")
		delete(additionalProperties, "feature_block_id")
		delete(additionalProperties, "instance")
		delete(additionalProperties, "source")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "updated_timestamp")
		delete(additionalProperties, "external_uid")
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "end_timestamp")
		delete(additionalProperties, "organiser")
		delete(additionalProperties, "attendee")
		delete(additionalProperties, "status")
		delete(additionalProperties, "location")
		delete(additionalProperties, "type")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "trigger")
		delete(additionalProperties, "action")
		delete(additionalProperties, "reminder_description")
		delete(additionalProperties, "duration_string")
		delete(additionalProperties, "duration_of_event")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineItemCalendarEvent struct {
	value *TimelineItemCalendarEvent
	isSet bool
}

func (v NullableTimelineItemCalendarEvent) Get() *TimelineItemCalendarEvent {
	return v.value
}

func (v *NullableTimelineItemCalendarEvent) Set(val *TimelineItemCalendarEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineItemCalendarEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineItemCalendarEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineItemCalendarEvent(val *TimelineItemCalendarEvent) *NullableTimelineItemCalendarEvent {
	return &NullableTimelineItemCalendarEvent{value: val, isSet: true}
}

func (v NullableTimelineItemCalendarEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineItemCalendarEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


