/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the AuthErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthErrorResponse{}

// AuthErrorResponse struct for AuthErrorResponse
type AuthErrorResponse struct {
	Error *AuthErrorResponseError `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthErrorResponse AuthErrorResponse

// NewAuthErrorResponse instantiates a new AuthErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthErrorResponse() *AuthErrorResponse {
	this := AuthErrorResponse{}
	return &this
}

// NewAuthErrorResponseWithDefaults instantiates a new AuthErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthErrorResponseWithDefaults() *AuthErrorResponse {
	this := AuthErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AuthErrorResponse) GetError() AuthErrorResponseError {
	if o == nil || IsNil(o.Error) {
		var ret AuthErrorResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthErrorResponse) GetErrorOk() (*AuthErrorResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AuthErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given AuthErrorResponseError and assigns it to the Error field.
func (o *AuthErrorResponse) SetError(v AuthErrorResponseError) {
	o.Error = &v
}

func (o AuthErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthErrorResponse) UnmarshalJSON(data []byte) (err error) {
	varAuthErrorResponse := _AuthErrorResponse{}

	err = json.Unmarshal(data, &varAuthErrorResponse)

	if err != nil {
		return err
	}

	*o = AuthErrorResponse(varAuthErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthErrorResponse struct {
	value *AuthErrorResponse
	isSet bool
}

func (v NullableAuthErrorResponse) Get() *AuthErrorResponse {
	return v.value
}

func (v *NullableAuthErrorResponse) Set(val *AuthErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthErrorResponse(val *AuthErrorResponse) *NullableAuthErrorResponse {
	return &NullableAuthErrorResponse{value: val, isSet: true}
}

func (v NullableAuthErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


