/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the SecureMessageConversationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureMessageConversationResponse{}

// SecureMessageConversationResponse Response containing all messages in a conversation
type SecureMessageConversationResponse struct {
	Messages []SecureMessage `json:"messages,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SecureMessageConversationResponse SecureMessageConversationResponse

// NewSecureMessageConversationResponse instantiates a new SecureMessageConversationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureMessageConversationResponse() *SecureMessageConversationResponse {
	this := SecureMessageConversationResponse{}
	return &this
}

// NewSecureMessageConversationResponseWithDefaults instantiates a new SecureMessageConversationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureMessageConversationResponseWithDefaults() *SecureMessageConversationResponse {
	this := SecureMessageConversationResponse{}
	return &this
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *SecureMessageConversationResponse) GetMessages() []SecureMessage {
	if o == nil || IsNil(o.Messages) {
		var ret []SecureMessage
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecureMessageConversationResponse) GetMessagesOk() ([]SecureMessage, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *SecureMessageConversationResponse) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []SecureMessage and assigns it to the Messages field.
func (o *SecureMessageConversationResponse) SetMessages(v []SecureMessage) {
	o.Messages = v
}

func (o SecureMessageConversationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureMessageConversationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureMessageConversationResponse) UnmarshalJSON(data []byte) (err error) {
	varSecureMessageConversationResponse := _SecureMessageConversationResponse{}

	err = json.Unmarshal(data, &varSecureMessageConversationResponse)

	if err != nil {
		return err
	}

	*o = SecureMessageConversationResponse(varSecureMessageConversationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "messages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureMessageConversationResponse struct {
	value *SecureMessageConversationResponse
	isSet bool
}

func (v NullableSecureMessageConversationResponse) Get() *SecureMessageConversationResponse {
	return v.value
}

func (v *NullableSecureMessageConversationResponse) Set(val *SecureMessageConversationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureMessageConversationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureMessageConversationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureMessageConversationResponse(val *SecureMessageConversationResponse) *NullableSecureMessageConversationResponse {
	return &NullableSecureMessageConversationResponse{value: val, isSet: true}
}

func (v NullableSecureMessageConversationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureMessageConversationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


