/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the ReferralListResponseReferralsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralListResponseReferralsInner{}

// ReferralListResponseReferralsInner struct for ReferralListResponseReferralsInner
type ReferralListResponseReferralsInner struct {
	Id *int32 `json:"id,omitempty"`
	CreatedTimestamp *int64 `json:"created_timestamp,omitempty"`
	ServiceId *int32 `json:"service_id,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
	ServiceDescription *string `json:"service_description,omitempty"`
	ServiceContactNumber *string `json:"service_contact_number,omitempty"`
	ServiceEmail *string `json:"service_email,omitempty"`
	ServiceUrl *string `json:"service_url,omitempty"`
	Type *string `json:"type,omitempty"`
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferralListResponseReferralsInner ReferralListResponseReferralsInner

// NewReferralListResponseReferralsInner instantiates a new ReferralListResponseReferralsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralListResponseReferralsInner() *ReferralListResponseReferralsInner {
	this := ReferralListResponseReferralsInner{}
	return &this
}

// NewReferralListResponseReferralsInnerWithDefaults instantiates a new ReferralListResponseReferralsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralListResponseReferralsInnerWithDefaults() *ReferralListResponseReferralsInner {
	this := ReferralListResponseReferralsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ReferralListResponseReferralsInner) SetId(v int32) {
	o.Id = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetCreatedTimestamp() int64 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int64
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetCreatedTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int64 and assigns it to the CreatedTimestamp field.
func (o *ReferralListResponseReferralsInner) SetCreatedTimestamp(v int64) {
	o.CreatedTimestamp = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceId() int32 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int32
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int32 and assigns it to the ServiceId field.
func (o *ReferralListResponseReferralsInner) SetServiceId(v int32) {
	o.ServiceId = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *ReferralListResponseReferralsInner) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetServiceDescription returns the ServiceDescription field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceDescription() string {
	if o == nil || IsNil(o.ServiceDescription) {
		var ret string
		return ret
	}
	return *o.ServiceDescription
}

// GetServiceDescriptionOk returns a tuple with the ServiceDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceDescription) {
		return nil, false
	}
	return o.ServiceDescription, true
}

// HasServiceDescription returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceDescription() bool {
	if o != nil && !IsNil(o.ServiceDescription) {
		return true
	}

	return false
}

// SetServiceDescription gets a reference to the given string and assigns it to the ServiceDescription field.
func (o *ReferralListResponseReferralsInner) SetServiceDescription(v string) {
	o.ServiceDescription = &v
}

// GetServiceContactNumber returns the ServiceContactNumber field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceContactNumber() string {
	if o == nil || IsNil(o.ServiceContactNumber) {
		var ret string
		return ret
	}
	return *o.ServiceContactNumber
}

// GetServiceContactNumberOk returns a tuple with the ServiceContactNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceContactNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceContactNumber) {
		return nil, false
	}
	return o.ServiceContactNumber, true
}

// HasServiceContactNumber returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceContactNumber() bool {
	if o != nil && !IsNil(o.ServiceContactNumber) {
		return true
	}

	return false
}

// SetServiceContactNumber gets a reference to the given string and assigns it to the ServiceContactNumber field.
func (o *ReferralListResponseReferralsInner) SetServiceContactNumber(v string) {
	o.ServiceContactNumber = &v
}

// GetServiceEmail returns the ServiceEmail field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceEmail() string {
	if o == nil || IsNil(o.ServiceEmail) {
		var ret string
		return ret
	}
	return *o.ServiceEmail
}

// GetServiceEmailOk returns a tuple with the ServiceEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceEmail) {
		return nil, false
	}
	return o.ServiceEmail, true
}

// HasServiceEmail returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceEmail() bool {
	if o != nil && !IsNil(o.ServiceEmail) {
		return true
	}

	return false
}

// SetServiceEmail gets a reference to the given string and assigns it to the ServiceEmail field.
func (o *ReferralListResponseReferralsInner) SetServiceEmail(v string) {
	o.ServiceEmail = &v
}

// GetServiceUrl returns the ServiceUrl field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetServiceUrl() string {
	if o == nil || IsNil(o.ServiceUrl) {
		var ret string
		return ret
	}
	return *o.ServiceUrl
}

// GetServiceUrlOk returns a tuple with the ServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetServiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUrl) {
		return nil, false
	}
	return o.ServiceUrl, true
}

// HasServiceUrl returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasServiceUrl() bool {
	if o != nil && !IsNil(o.ServiceUrl) {
		return true
	}

	return false
}

// SetServiceUrl gets a reference to the given string and assigns it to the ServiceUrl field.
func (o *ReferralListResponseReferralsInner) SetServiceUrl(v string) {
	o.ServiceUrl = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReferralListResponseReferralsInner) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReferralListResponseReferralsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralListResponseReferralsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReferralListResponseReferralsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReferralListResponseReferralsInner) SetStatus(v string) {
	o.Status = &v
}

func (o ReferralListResponseReferralsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralListResponseReferralsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	if !IsNil(o.ServiceDescription) {
		toSerialize["service_description"] = o.ServiceDescription
	}
	if !IsNil(o.ServiceContactNumber) {
		toSerialize["service_contact_number"] = o.ServiceContactNumber
	}
	if !IsNil(o.ServiceEmail) {
		toSerialize["service_email"] = o.ServiceEmail
	}
	if !IsNil(o.ServiceUrl) {
		toSerialize["service_url"] = o.ServiceUrl
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralListResponseReferralsInner) UnmarshalJSON(data []byte) (err error) {
	varReferralListResponseReferralsInner := _ReferralListResponseReferralsInner{}

	err = json.Unmarshal(data, &varReferralListResponseReferralsInner)

	if err != nil {
		return err
	}

	*o = ReferralListResponseReferralsInner(varReferralListResponseReferralsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "service_id")
		delete(additionalProperties, "service_name")
		delete(additionalProperties, "service_description")
		delete(additionalProperties, "service_contact_number")
		delete(additionalProperties, "service_email")
		delete(additionalProperties, "service_url")
		delete(additionalProperties, "type")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralListResponseReferralsInner struct {
	value *ReferralListResponseReferralsInner
	isSet bool
}

func (v NullableReferralListResponseReferralsInner) Get() *ReferralListResponseReferralsInner {
	return v.value
}

func (v *NullableReferralListResponseReferralsInner) Set(val *ReferralListResponseReferralsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralListResponseReferralsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralListResponseReferralsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralListResponseReferralsInner(val *ReferralListResponseReferralsInner) *NullableReferralListResponseReferralsInner {
	return &NullableReferralListResponseReferralsInner{value: val, isSet: true}
}

func (v NullableReferralListResponseReferralsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralListResponseReferralsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


