/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the ReferralCommonRequestBodyFieldsReferreeAvailability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralCommonRequestBodyFieldsReferreeAvailability{}

// ReferralCommonRequestBodyFieldsReferreeAvailability Availability of the referree. If not provided, defaults to empty AM/PM arrays.
type ReferralCommonRequestBodyFieldsReferreeAvailability struct {
	// Morning availability slots
	AM []string `json:"AM,omitempty"`
	// Afternoon availability slots
	PM []string `json:"PM,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferralCommonRequestBodyFieldsReferreeAvailability ReferralCommonRequestBodyFieldsReferreeAvailability

// NewReferralCommonRequestBodyFieldsReferreeAvailability instantiates a new ReferralCommonRequestBodyFieldsReferreeAvailability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralCommonRequestBodyFieldsReferreeAvailability() *ReferralCommonRequestBodyFieldsReferreeAvailability {
	this := ReferralCommonRequestBodyFieldsReferreeAvailability{}
	return &this
}

// NewReferralCommonRequestBodyFieldsReferreeAvailabilityWithDefaults instantiates a new ReferralCommonRequestBodyFieldsReferreeAvailability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralCommonRequestBodyFieldsReferreeAvailabilityWithDefaults() *ReferralCommonRequestBodyFieldsReferreeAvailability {
	this := ReferralCommonRequestBodyFieldsReferreeAvailability{}
	return &this
}

// GetAM returns the AM field value if set, zero value otherwise.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) GetAM() []string {
	if o == nil || IsNil(o.AM) {
		var ret []string
		return ret
	}
	return o.AM
}

// GetAMOk returns a tuple with the AM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) GetAMOk() ([]string, bool) {
	if o == nil || IsNil(o.AM) {
		return nil, false
	}
	return o.AM, true
}

// HasAM returns a boolean if a field has been set.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) HasAM() bool {
	if o != nil && !IsNil(o.AM) {
		return true
	}

	return false
}

// SetAM gets a reference to the given []string and assigns it to the AM field.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) SetAM(v []string) {
	o.AM = v
}

// GetPM returns the PM field value if set, zero value otherwise.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) GetPM() []string {
	if o == nil || IsNil(o.PM) {
		var ret []string
		return ret
	}
	return o.PM
}

// GetPMOk returns a tuple with the PM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) GetPMOk() ([]string, bool) {
	if o == nil || IsNil(o.PM) {
		return nil, false
	}
	return o.PM, true
}

// HasPM returns a boolean if a field has been set.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) HasPM() bool {
	if o != nil && !IsNil(o.PM) {
		return true
	}

	return false
}

// SetPM gets a reference to the given []string and assigns it to the PM field.
func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) SetPM(v []string) {
	o.PM = v
}

func (o ReferralCommonRequestBodyFieldsReferreeAvailability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralCommonRequestBodyFieldsReferreeAvailability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AM) {
		toSerialize["AM"] = o.AM
	}
	if !IsNil(o.PM) {
		toSerialize["PM"] = o.PM
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralCommonRequestBodyFieldsReferreeAvailability) UnmarshalJSON(data []byte) (err error) {
	varReferralCommonRequestBodyFieldsReferreeAvailability := _ReferralCommonRequestBodyFieldsReferreeAvailability{}

	err = json.Unmarshal(data, &varReferralCommonRequestBodyFieldsReferreeAvailability)

	if err != nil {
		return err
	}

	*o = ReferralCommonRequestBodyFieldsReferreeAvailability(varReferralCommonRequestBodyFieldsReferreeAvailability)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "AM")
		delete(additionalProperties, "PM")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralCommonRequestBodyFieldsReferreeAvailability struct {
	value *ReferralCommonRequestBodyFieldsReferreeAvailability
	isSet bool
}

func (v NullableReferralCommonRequestBodyFieldsReferreeAvailability) Get() *ReferralCommonRequestBodyFieldsReferreeAvailability {
	return v.value
}

func (v *NullableReferralCommonRequestBodyFieldsReferreeAvailability) Set(val *ReferralCommonRequestBodyFieldsReferreeAvailability) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralCommonRequestBodyFieldsReferreeAvailability) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralCommonRequestBodyFieldsReferreeAvailability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralCommonRequestBodyFieldsReferreeAvailability(val *ReferralCommonRequestBodyFieldsReferreeAvailability) *NullableReferralCommonRequestBodyFieldsReferreeAvailability {
	return &NullableReferralCommonRequestBodyFieldsReferreeAvailability{value: val, isSet: true}
}

func (v NullableReferralCommonRequestBodyFieldsReferreeAvailability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralCommonRequestBodyFieldsReferreeAvailability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


