/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureMessageSendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureMessageSendRequest{}

// SecureMessageSendRequest Request to send a secure message
type SecureMessageSendRequest struct {
	// Content of the message
	MessageContent string `json:"message_content"`
	// ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context.
	ConversationId string `json:"conversation_id"`
	// Recipient user ID
	MessageTo string `json:"message_to"`
	AdditionalProperties map[string]interface{}
}

type _SecureMessageSendRequest SecureMessageSendRequest

// NewSecureMessageSendRequest instantiates a new SecureMessageSendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureMessageSendRequest(messageContent string, conversationId string, messageTo string) *SecureMessageSendRequest {
	this := SecureMessageSendRequest{}
	this.MessageContent = messageContent
	this.ConversationId = conversationId
	this.MessageTo = messageTo
	return &this
}

// NewSecureMessageSendRequestWithDefaults instantiates a new SecureMessageSendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureMessageSendRequestWithDefaults() *SecureMessageSendRequest {
	this := SecureMessageSendRequest{}
	return &this
}

// GetMessageContent returns the MessageContent field value
func (o *SecureMessageSendRequest) GetMessageContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value
// and a boolean to check if the value has been set.
func (o *SecureMessageSendRequest) GetMessageContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageContent, true
}

// SetMessageContent sets field value
func (o *SecureMessageSendRequest) SetMessageContent(v string) {
	o.MessageContent = v
}

// GetConversationId returns the ConversationId field value
func (o *SecureMessageSendRequest) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *SecureMessageSendRequest) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *SecureMessageSendRequest) SetConversationId(v string) {
	o.ConversationId = v
}

// GetMessageTo returns the MessageTo field value
func (o *SecureMessageSendRequest) GetMessageTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageTo
}

// GetMessageToOk returns a tuple with the MessageTo field value
// and a boolean to check if the value has been set.
func (o *SecureMessageSendRequest) GetMessageToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageTo, true
}

// SetMessageTo sets field value
func (o *SecureMessageSendRequest) SetMessageTo(v string) {
	o.MessageTo = v
}

func (o SecureMessageSendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureMessageSendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message_content"] = o.MessageContent
	toSerialize["conversation_id"] = o.ConversationId
	toSerialize["message_to"] = o.MessageTo

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureMessageSendRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message_content",
		"conversation_id",
		"message_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureMessageSendRequest := _SecureMessageSendRequest{}

	err = json.Unmarshal(data, &varSecureMessageSendRequest)

	if err != nil {
		return err
	}

	*o = SecureMessageSendRequest(varSecureMessageSendRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message_content")
		delete(additionalProperties, "conversation_id")
		delete(additionalProperties, "message_to")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureMessageSendRequest struct {
	value *SecureMessageSendRequest
	isSet bool
}

func (v NullableSecureMessageSendRequest) Get() *SecureMessageSendRequest {
	return v.value
}

func (v *NullableSecureMessageSendRequest) Set(val *SecureMessageSendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureMessageSendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureMessageSendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureMessageSendRequest(val *SecureMessageSendRequest) *NullableSecureMessageSendRequest {
	return &NullableSecureMessageSendRequest{value: val, isSet: true}
}

func (v NullableSecureMessageSendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureMessageSendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


