/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
)

// checks if the TimelineResponseTimelineInnerOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimelineResponseTimelineInnerOneOf1{}

// TimelineResponseTimelineInnerOneOf1 Secure message item
type TimelineResponseTimelineInnerOneOf1 struct {
	Id *int32 `json:"id,omitempty"`
	FeatureBlock *string `json:"feature_block,omitempty"`
	FeatureBlockId *string `json:"feature_block_id,omitempty"`
	StartTimestamp *string `json:"start_timestamp,omitempty"`
	ItemTimestamp *int32 `json:"item_timestamp,omitempty"`
	CreatedTimestamp *int32 `json:"created_timestamp,omitempty"`
	MessageFrom *string `json:"message_from,omitempty"`
	MessageTo *string `json:"message_to,omitempty"`
	MessageContent *string `json:"message_content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TimelineResponseTimelineInnerOneOf1 TimelineResponseTimelineInnerOneOf1

// NewTimelineResponseTimelineInnerOneOf1 instantiates a new TimelineResponseTimelineInnerOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimelineResponseTimelineInnerOneOf1() *TimelineResponseTimelineInnerOneOf1 {
	this := TimelineResponseTimelineInnerOneOf1{}
	return &this
}

// NewTimelineResponseTimelineInnerOneOf1WithDefaults instantiates a new TimelineResponseTimelineInnerOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimelineResponseTimelineInnerOneOf1WithDefaults() *TimelineResponseTimelineInnerOneOf1 {
	this := TimelineResponseTimelineInnerOneOf1{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *TimelineResponseTimelineInnerOneOf1) SetId(v int32) {
	o.Id = &v
}

// GetFeatureBlock returns the FeatureBlock field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetFeatureBlock() string {
	if o == nil || IsNil(o.FeatureBlock) {
		var ret string
		return ret
	}
	return *o.FeatureBlock
}

// GetFeatureBlockOk returns a tuple with the FeatureBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetFeatureBlockOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlock) {
		return nil, false
	}
	return o.FeatureBlock, true
}

// HasFeatureBlock returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasFeatureBlock() bool {
	if o != nil && !IsNil(o.FeatureBlock) {
		return true
	}

	return false
}

// SetFeatureBlock gets a reference to the given string and assigns it to the FeatureBlock field.
func (o *TimelineResponseTimelineInnerOneOf1) SetFeatureBlock(v string) {
	o.FeatureBlock = &v
}

// GetFeatureBlockId returns the FeatureBlockId field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetFeatureBlockId() string {
	if o == nil || IsNil(o.FeatureBlockId) {
		var ret string
		return ret
	}
	return *o.FeatureBlockId
}

// GetFeatureBlockIdOk returns a tuple with the FeatureBlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetFeatureBlockIdOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureBlockId) {
		return nil, false
	}
	return o.FeatureBlockId, true
}

// HasFeatureBlockId returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasFeatureBlockId() bool {
	if o != nil && !IsNil(o.FeatureBlockId) {
		return true
	}

	return false
}

// SetFeatureBlockId gets a reference to the given string and assigns it to the FeatureBlockId field.
func (o *TimelineResponseTimelineInnerOneOf1) SetFeatureBlockId(v string) {
	o.FeatureBlockId = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetStartTimestamp() string {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret string
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetStartTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given string and assigns it to the StartTimestamp field.
func (o *TimelineResponseTimelineInnerOneOf1) SetStartTimestamp(v string) {
	o.StartTimestamp = &v
}

// GetItemTimestamp returns the ItemTimestamp field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetItemTimestamp() int32 {
	if o == nil || IsNil(o.ItemTimestamp) {
		var ret int32
		return ret
	}
	return *o.ItemTimestamp
}

// GetItemTimestampOk returns a tuple with the ItemTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetItemTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.ItemTimestamp) {
		return nil, false
	}
	return o.ItemTimestamp, true
}

// HasItemTimestamp returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasItemTimestamp() bool {
	if o != nil && !IsNil(o.ItemTimestamp) {
		return true
	}

	return false
}

// SetItemTimestamp gets a reference to the given int32 and assigns it to the ItemTimestamp field.
func (o *TimelineResponseTimelineInnerOneOf1) SetItemTimestamp(v int32) {
	o.ItemTimestamp = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetCreatedTimestamp() int32 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int32
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetCreatedTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int32 and assigns it to the CreatedTimestamp field.
func (o *TimelineResponseTimelineInnerOneOf1) SetCreatedTimestamp(v int32) {
	o.CreatedTimestamp = &v
}

// GetMessageFrom returns the MessageFrom field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageFrom() string {
	if o == nil || IsNil(o.MessageFrom) {
		var ret string
		return ret
	}
	return *o.MessageFrom
}

// GetMessageFromOk returns a tuple with the MessageFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageFromOk() (*string, bool) {
	if o == nil || IsNil(o.MessageFrom) {
		return nil, false
	}
	return o.MessageFrom, true
}

// HasMessageFrom returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasMessageFrom() bool {
	if o != nil && !IsNil(o.MessageFrom) {
		return true
	}

	return false
}

// SetMessageFrom gets a reference to the given string and assigns it to the MessageFrom field.
func (o *TimelineResponseTimelineInnerOneOf1) SetMessageFrom(v string) {
	o.MessageFrom = &v
}

// GetMessageTo returns the MessageTo field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageTo() string {
	if o == nil || IsNil(o.MessageTo) {
		var ret string
		return ret
	}
	return *o.MessageTo
}

// GetMessageToOk returns a tuple with the MessageTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageToOk() (*string, bool) {
	if o == nil || IsNil(o.MessageTo) {
		return nil, false
	}
	return o.MessageTo, true
}

// HasMessageTo returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasMessageTo() bool {
	if o != nil && !IsNil(o.MessageTo) {
		return true
	}

	return false
}

// SetMessageTo gets a reference to the given string and assigns it to the MessageTo field.
func (o *TimelineResponseTimelineInnerOneOf1) SetMessageTo(v string) {
	o.MessageTo = &v
}

// GetMessageContent returns the MessageContent field value if set, zero value otherwise.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageContent() string {
	if o == nil || IsNil(o.MessageContent) {
		var ret string
		return ret
	}
	return *o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimelineResponseTimelineInnerOneOf1) GetMessageContentOk() (*string, bool) {
	if o == nil || IsNil(o.MessageContent) {
		return nil, false
	}
	return o.MessageContent, true
}

// HasMessageContent returns a boolean if a field has been set.
func (o *TimelineResponseTimelineInnerOneOf1) HasMessageContent() bool {
	if o != nil && !IsNil(o.MessageContent) {
		return true
	}

	return false
}

// SetMessageContent gets a reference to the given string and assigns it to the MessageContent field.
func (o *TimelineResponseTimelineInnerOneOf1) SetMessageContent(v string) {
	o.MessageContent = &v
}

func (o TimelineResponseTimelineInnerOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimelineResponseTimelineInnerOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FeatureBlock) {
		toSerialize["feature_block"] = o.FeatureBlock
	}
	if !IsNil(o.FeatureBlockId) {
		toSerialize["feature_block_id"] = o.FeatureBlockId
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.ItemTimestamp) {
		toSerialize["item_timestamp"] = o.ItemTimestamp
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.MessageFrom) {
		toSerialize["message_from"] = o.MessageFrom
	}
	if !IsNil(o.MessageTo) {
		toSerialize["message_to"] = o.MessageTo
	}
	if !IsNil(o.MessageContent) {
		toSerialize["message_content"] = o.MessageContent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TimelineResponseTimelineInnerOneOf1) UnmarshalJSON(data []byte) (err error) {
	varTimelineResponseTimelineInnerOneOf1 := _TimelineResponseTimelineInnerOneOf1{}

	err = json.Unmarshal(data, &varTimelineResponseTimelineInnerOneOf1)

	if err != nil {
		return err
	}

	*o = TimelineResponseTimelineInnerOneOf1(varTimelineResponseTimelineInnerOneOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "feature_block")
		delete(additionalProperties, "feature_block_id")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "item_timestamp")
		delete(additionalProperties, "created_timestamp")
		delete(additionalProperties, "message_from")
		delete(additionalProperties, "message_to")
		delete(additionalProperties, "message_content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTimelineResponseTimelineInnerOneOf1 struct {
	value *TimelineResponseTimelineInnerOneOf1
	isSet bool
}

func (v NullableTimelineResponseTimelineInnerOneOf1) Get() *TimelineResponseTimelineInnerOneOf1 {
	return v.value
}

func (v *NullableTimelineResponseTimelineInnerOneOf1) Set(val *TimelineResponseTimelineInnerOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTimelineResponseTimelineInnerOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTimelineResponseTimelineInnerOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimelineResponseTimelineInnerOneOf1(val *TimelineResponseTimelineInnerOneOf1) *NullableTimelineResponseTimelineInnerOneOf1 {
	return &NullableTimelineResponseTimelineInnerOneOf1{value: val, isSet: true}
}

func (v NullableTimelineResponseTimelineInnerOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimelineResponseTimelineInnerOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


