/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ReferralStatusUpdateRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferralStatusUpdateRequestBody{}

// ReferralStatusUpdateRequestBody Fields for updating the status of a referral (e.g. from 'Referred' to 'Accepted')
type ReferralStatusUpdateRequestBody struct {
	// ID of the referral to be updated
	Id int32 `json:"id"`
	// Status the referral is to be updated to
	Status string `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _ReferralStatusUpdateRequestBody ReferralStatusUpdateRequestBody

// NewReferralStatusUpdateRequestBody instantiates a new ReferralStatusUpdateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferralStatusUpdateRequestBody(id int32, status string) *ReferralStatusUpdateRequestBody {
	this := ReferralStatusUpdateRequestBody{}
	this.Id = id
	this.Status = status
	return &this
}

// NewReferralStatusUpdateRequestBodyWithDefaults instantiates a new ReferralStatusUpdateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferralStatusUpdateRequestBodyWithDefaults() *ReferralStatusUpdateRequestBody {
	this := ReferralStatusUpdateRequestBody{}
	return &this
}

// GetId returns the Id field value
func (o *ReferralStatusUpdateRequestBody) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReferralStatusUpdateRequestBody) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReferralStatusUpdateRequestBody) SetId(v int32) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *ReferralStatusUpdateRequestBody) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReferralStatusUpdateRequestBody) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReferralStatusUpdateRequestBody) SetStatus(v string) {
	o.Status = v
}

func (o ReferralStatusUpdateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferralStatusUpdateRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferralStatusUpdateRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReferralStatusUpdateRequestBody := _ReferralStatusUpdateRequestBody{}

	err = json.Unmarshal(data, &varReferralStatusUpdateRequestBody)

	if err != nil {
		return err
	}

	*o = ReferralStatusUpdateRequestBody(varReferralStatusUpdateRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferralStatusUpdateRequestBody struct {
	value *ReferralStatusUpdateRequestBody
	isSet bool
}

func (v NullableReferralStatusUpdateRequestBody) Get() *ReferralStatusUpdateRequestBody {
	return v.value
}

func (v *NullableReferralStatusUpdateRequestBody) Set(val *ReferralStatusUpdateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableReferralStatusUpdateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableReferralStatusUpdateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferralStatusUpdateRequestBody(val *ReferralStatusUpdateRequestBody) *NullableReferralStatusUpdateRequestBody {
	return &NullableReferralStatusUpdateRequestBody{value: val, isSet: true}
}

func (v NullableReferralStatusUpdateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferralStatusUpdateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


