/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SecureMessageReceiveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecureMessageReceiveRequest{}

// SecureMessageReceiveRequest Request to receive a secure message
type SecureMessageReceiveRequest struct {
	// Content of the message
	MessageContent string `json:"message_content"`
	// ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context.
	ConversationId string `json:"conversation_id"`
	// Sender user ID
	MessageFrom string `json:"message_from"`
	AdditionalProperties map[string]interface{}
}

type _SecureMessageReceiveRequest SecureMessageReceiveRequest

// NewSecureMessageReceiveRequest instantiates a new SecureMessageReceiveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecureMessageReceiveRequest(messageContent string, conversationId string, messageFrom string) *SecureMessageReceiveRequest {
	this := SecureMessageReceiveRequest{}
	this.MessageContent = messageContent
	this.ConversationId = conversationId
	this.MessageFrom = messageFrom
	return &this
}

// NewSecureMessageReceiveRequestWithDefaults instantiates a new SecureMessageReceiveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecureMessageReceiveRequestWithDefaults() *SecureMessageReceiveRequest {
	this := SecureMessageReceiveRequest{}
	return &this
}

// GetMessageContent returns the MessageContent field value
func (o *SecureMessageReceiveRequest) GetMessageContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageContent
}

// GetMessageContentOk returns a tuple with the MessageContent field value
// and a boolean to check if the value has been set.
func (o *SecureMessageReceiveRequest) GetMessageContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageContent, true
}

// SetMessageContent sets field value
func (o *SecureMessageReceiveRequest) SetMessageContent(v string) {
	o.MessageContent = v
}

// GetConversationId returns the ConversationId field value
func (o *SecureMessageReceiveRequest) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *SecureMessageReceiveRequest) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *SecureMessageReceiveRequest) SetConversationId(v string) {
	o.ConversationId = v
}

// GetMessageFrom returns the MessageFrom field value
func (o *SecureMessageReceiveRequest) GetMessageFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageFrom
}

// GetMessageFromOk returns a tuple with the MessageFrom field value
// and a boolean to check if the value has been set.
func (o *SecureMessageReceiveRequest) GetMessageFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageFrom, true
}

// SetMessageFrom sets field value
func (o *SecureMessageReceiveRequest) SetMessageFrom(v string) {
	o.MessageFrom = v
}

func (o SecureMessageReceiveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecureMessageReceiveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message_content"] = o.MessageContent
	toSerialize["conversation_id"] = o.ConversationId
	toSerialize["message_from"] = o.MessageFrom

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecureMessageReceiveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message_content",
		"conversation_id",
		"message_from",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecureMessageReceiveRequest := _SecureMessageReceiveRequest{}

	err = json.Unmarshal(data, &varSecureMessageReceiveRequest)

	if err != nil {
		return err
	}

	*o = SecureMessageReceiveRequest(varSecureMessageReceiveRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message_content")
		delete(additionalProperties, "conversation_id")
		delete(additionalProperties, "message_from")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecureMessageReceiveRequest struct {
	value *SecureMessageReceiveRequest
	isSet bool
}

func (v NullableSecureMessageReceiveRequest) Get() *SecureMessageReceiveRequest {
	return v.value
}

func (v *NullableSecureMessageReceiveRequest) Set(val *SecureMessageReceiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecureMessageReceiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecureMessageReceiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecureMessageReceiveRequest(val *SecureMessageReceiveRequest) *NullableSecureMessageReceiveRequest {
	return &NullableSecureMessageReceiveRequest{value: val, isSet: true}
}

func (v NullableSecureMessageReceiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecureMessageReceiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


