/*
PDX API

API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apipdxsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CalendarEventUpdateRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarEventUpdateRequestBody{}

// CalendarEventUpdateRequestBody Fields for updating a calendar event. Only supplied fields will be updated. At least one field other than 'id' must be provided.
type CalendarEventUpdateRequestBody struct {
	// Title of the event
	Title *string `json:"title,omitempty"`
	// Detailed description of the event
	Description *string `json:"description,omitempty"`
	// Start date and time as Unix timestamp
	StartTimestamp *int64 `json:"start_timestamp,omitempty"`
	// End date and time as Unix timestamp
	EndTimestamp *int64 `json:"end_timestamp,omitempty"`
	// Status of the event
	Status *string `json:"status,omitempty"`
	// Creator of the event
	Organiser *string `json:"organiser,omitempty"`
	// Person attending the event
	Attendee *string `json:"attendee,omitempty"`
	// Event location
	Location *string `json:"location,omitempty"`
	// ID of the calendar-event to be updated
	Id int32 `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _CalendarEventUpdateRequestBody CalendarEventUpdateRequestBody

// NewCalendarEventUpdateRequestBody instantiates a new CalendarEventUpdateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarEventUpdateRequestBody(id int32) *CalendarEventUpdateRequestBody {
	this := CalendarEventUpdateRequestBody{}
	var status string = "TENTATIVE"
	this.Status = &status
	this.Id = id
	return &this
}

// NewCalendarEventUpdateRequestBodyWithDefaults instantiates a new CalendarEventUpdateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarEventUpdateRequestBodyWithDefaults() *CalendarEventUpdateRequestBody {
	this := CalendarEventUpdateRequestBody{}
	var status string = "TENTATIVE"
	this.Status = &status
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CalendarEventUpdateRequestBody) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CalendarEventUpdateRequestBody) SetDescription(v string) {
	o.Description = &v
}

// GetStartTimestamp returns the StartTimestamp field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetStartTimestamp() int64 {
	if o == nil || IsNil(o.StartTimestamp) {
		var ret int64
		return ret
	}
	return *o.StartTimestamp
}

// GetStartTimestampOk returns a tuple with the StartTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetStartTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTimestamp) {
		return nil, false
	}
	return o.StartTimestamp, true
}

// HasStartTimestamp returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasStartTimestamp() bool {
	if o != nil && !IsNil(o.StartTimestamp) {
		return true
	}

	return false
}

// SetStartTimestamp gets a reference to the given int64 and assigns it to the StartTimestamp field.
func (o *CalendarEventUpdateRequestBody) SetStartTimestamp(v int64) {
	o.StartTimestamp = &v
}

// GetEndTimestamp returns the EndTimestamp field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetEndTimestamp() int64 {
	if o == nil || IsNil(o.EndTimestamp) {
		var ret int64
		return ret
	}
	return *o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetEndTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTimestamp) {
		return nil, false
	}
	return o.EndTimestamp, true
}

// HasEndTimestamp returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasEndTimestamp() bool {
	if o != nil && !IsNil(o.EndTimestamp) {
		return true
	}

	return false
}

// SetEndTimestamp gets a reference to the given int64 and assigns it to the EndTimestamp field.
func (o *CalendarEventUpdateRequestBody) SetEndTimestamp(v int64) {
	o.EndTimestamp = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CalendarEventUpdateRequestBody) SetStatus(v string) {
	o.Status = &v
}

// GetOrganiser returns the Organiser field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetOrganiser() string {
	if o == nil || IsNil(o.Organiser) {
		var ret string
		return ret
	}
	return *o.Organiser
}

// GetOrganiserOk returns a tuple with the Organiser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetOrganiserOk() (*string, bool) {
	if o == nil || IsNil(o.Organiser) {
		return nil, false
	}
	return o.Organiser, true
}

// HasOrganiser returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasOrganiser() bool {
	if o != nil && !IsNil(o.Organiser) {
		return true
	}

	return false
}

// SetOrganiser gets a reference to the given string and assigns it to the Organiser field.
func (o *CalendarEventUpdateRequestBody) SetOrganiser(v string) {
	o.Organiser = &v
}

// GetAttendee returns the Attendee field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetAttendee() string {
	if o == nil || IsNil(o.Attendee) {
		var ret string
		return ret
	}
	return *o.Attendee
}

// GetAttendeeOk returns a tuple with the Attendee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetAttendeeOk() (*string, bool) {
	if o == nil || IsNil(o.Attendee) {
		return nil, false
	}
	return o.Attendee, true
}

// HasAttendee returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasAttendee() bool {
	if o != nil && !IsNil(o.Attendee) {
		return true
	}

	return false
}

// SetAttendee gets a reference to the given string and assigns it to the Attendee field.
func (o *CalendarEventUpdateRequestBody) SetAttendee(v string) {
	o.Attendee = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *CalendarEventUpdateRequestBody) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *CalendarEventUpdateRequestBody) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *CalendarEventUpdateRequestBody) SetLocation(v string) {
	o.Location = &v
}

// GetId returns the Id field value
func (o *CalendarEventUpdateRequestBody) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CalendarEventUpdateRequestBody) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CalendarEventUpdateRequestBody) SetId(v int32) {
	o.Id = v
}

func (o CalendarEventUpdateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarEventUpdateRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartTimestamp) {
		toSerialize["start_timestamp"] = o.StartTimestamp
	}
	if !IsNil(o.EndTimestamp) {
		toSerialize["end_timestamp"] = o.EndTimestamp
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Organiser) {
		toSerialize["organiser"] = o.Organiser
	}
	if !IsNil(o.Attendee) {
		toSerialize["attendee"] = o.Attendee
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CalendarEventUpdateRequestBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarEventUpdateRequestBody := _CalendarEventUpdateRequestBody{}

	err = json.Unmarshal(data, &varCalendarEventUpdateRequestBody)

	if err != nil {
		return err
	}

	*o = CalendarEventUpdateRequestBody(varCalendarEventUpdateRequestBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "title")
		delete(additionalProperties, "description")
		delete(additionalProperties, "start_timestamp")
		delete(additionalProperties, "end_timestamp")
		delete(additionalProperties, "status")
		delete(additionalProperties, "organiser")
		delete(additionalProperties, "attendee")
		delete(additionalProperties, "location")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCalendarEventUpdateRequestBody struct {
	value *CalendarEventUpdateRequestBody
	isSet bool
}

func (v NullableCalendarEventUpdateRequestBody) Get() *CalendarEventUpdateRequestBody {
	return v.value
}

func (v *NullableCalendarEventUpdateRequestBody) Set(val *CalendarEventUpdateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarEventUpdateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarEventUpdateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarEventUpdateRequestBody(val *CalendarEventUpdateRequestBody) *NullableCalendarEventUpdateRequestBody {
	return &NullableCalendarEventUpdateRequestBody{value: val, isSet: true}
}

func (v NullableCalendarEventUpdateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarEventUpdateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


