openapi: 3.0.0
info:
  description: "API for processing subscribers requests to the PDX API to retrieve\
    \ one or more combinations of data, deliver and update records in a Members PDS\
    \ and ensure record integrity is maintained."
  title: PDX API
  version: 1.0.0
servers:
- description: PDX-API host.
  url: https://api.mydex.org
tags:
- description: Operations related to calendar events
  name: Calendar
- description: Operations related to referrals
  name: Referrals
- description: Operations related to secure messages
  name: Secure Messages
- description: Operations related to timeline
  name: Timeline
paths:
  /calendar/add-event:
    post:
      description: Creates a new event in the user's calendar.
      operationId: postCalendarEvent
      security:
      - oauth2:
        - post:/calendar/add-event
        - mydex:pdx
      summary: Supports adding a calendar-event.
      tags:
      - Calendar
  /calendar/add-appointment:
    post:
      description: Creates a new appointment in the user's calendar. An appointment
        must be made within a specified context e.g. a 'Referral'
      operationId: postCalendarAppointment
      security:
      - oauth2:
        - post:/calendar/add-appointment
        - mydex:pdx
      summary: Supports adding a calendar-appointment.
      tags:
      - Calendar
  /calendar/get-events:
    get:
      description: Returns a list of calendar events.
      operationId: getCalendarEvents
      security:
      - oauth2:
        - get:/calendar/get-events
        - mydex:pdx
      summary: Retrieve calendar events
      tags:
      - Calendar
  /calendar/get-appointments:
    get:
      description: Returns a list of appointments filtered by context and context_id.
      operationId: getCalendarAppointments
      security:
      - oauth2:
        - get:/calendar/get-appointments
        - mydex:pdx
      summary: Retrieve appointments for a given context
      tags:
      - Calendar
  /calendar/update-event:
    put:
      description: "Updates an event in the user's calendar. For example, updating\
        \ the 'status' from 'INVITED' to 'CONFIRMED' when a user accepts the invitation\
        \ to an appointment."
      operationId: putCalendarEvent
      security:
      - oauth2:
        - put:/calendar/update-event
        - mydex:pdx
      summary: Supports updating a calendar-event.
      tags:
      - Calendar
  /calendar/delete-event:
    delete:
      description: Deletes an event in the user's calendar.
      operationId: deleteCalendarEvent
      security:
      - oauth2:
        - delete:/calendar/delete-event
        - mydex:pdx
      summary: Supports deleting a calendar-event.
      tags:
      - Calendar
  /referrals/self-refer:
    post:
      description: Creates a new referral of type 'Self Referred' in the member's
        PDS.
      operationId: postSelfReferral
      security:
      - oauth2:
        - post:/referrals/self-refer
        - mydex:pdx
      summary: Supports self-referral.
      tags:
      - Referrals
  /referrals/read-all:
    get:
      description: Returns a list of referrals.
      operationId: getAllReferrals
      security:
      - oauth2:
        - get:/referrals/read-all
        - mydex:pdx
      summary: Retrieve rall referrals for a given member.
      tags:
      - Referrals
  /referrals/read-single:
    get:
      description: Returns the requested referral.
      operationId: getSingleReferral
      security:
      - oauth2:
        - get:/referrals/read-single
        - mydex:pdx
      summary: Retrieve a single referral by id for a given member.
      tags:
      - Referrals
  /referrals/update-status:
    put:
      description: "Updates the status of a member's referral specified by id. For\
        \ example, having been referred to a service, the status is set by default\
        \ to 'Referred' and this route enables it to be updated to 'Accepted' or 'Rejected'"
      operationId: updateReferralStatus
      security:
      - oauth2:
        - put:/referrals/update-status
        - mydex:pdx
      summary: Supports updating the status of a referral.
      tags:
      - Referrals
  /secure-messages/send:
    post:
      description: Creates a new sent message in the member's PDS.
      operationId: postSecureMessageSend
      security:
      - oauth2:
        - post:/secure-messages/send
        - mydex:pdx
      summary: Supports sending a message from the member's PDS.
      tags:
      - Secure Messages
  /secure-messages/receive:
    post:
      description: Creates a new received message in the member's PDS.
      operationId: postSecureMessageReceive
      security:
      - oauth2:
        - post:/secure-messages/receive
        - mydex:pdx
      summary: Supports sending a message to the member's PDS.
      tags:
      - Secure Messages
  /secure-messages/conversation:
    get:
      description: Returns a list of secure messages that form part of a conversation.
      operationId: getSecureMessageConversation
      security:
      - oauth2:
        - get:/secure-messages/conversation
        - mydex:pdx
      summary: Retrieve all secure messages for a given conversation.
      tags:
      - Secure Messages
  /timeline:
    get:
      description: "Returns a list of timeline items which includes: referrals, calendar\
        \ events and secure messages."
      operationId: getTimeline
      security:
      - oauth2:
        - get:/timeline
        - mydex:pdx
      summary: Retrieve list of timeline items.
      tags:
      - Timeline
  /timeline/single-item:
    get:
      description: Returns a single timeline item based on feature block and feature
        block id requested e.g. a 'referral' with id 123.
      operationId: getTimelineItem
      security:
      - oauth2:
        - get:/timeline/single-item
        - mydex:pdx
      summary: Retrieve a single timeline item.
      tags:
      - Timeline
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            mydex:pdx: Global access scope
            post:/calendar/add-event: Create a calendar event
            post:/calendar/add-appointment: Create a calendar appointment
            put:/calendar/update-event: Update a calendar event
            delete:/calendar/delete-event: Delete a calendar event
            get:/calendar/get-events: Read calendar events
            get:/calendar/get-appointments: Read calendar appointments
            post:/referrals/self-refer: Make a self-referral to a service
            get:/referrals/read-all: Read all referrals
            get:/referrals/read-single: Read a single referral
            put:/referrals/update-status: Update the status of a referral
            post:/secure-messages/send: Send a message FROM the member's PDS
            post:/secure-messages/receive: Send a message TO the member's PDS
            get:/secure-messages/conversation: Read messages grouped by the specified
              conversation
            get:/timeline: Read a list of timeline items
            get:/timeline/single-item: Read a single item from the timeline
          tokenUrl: https://op.mydexid.org/oauth2/token
      type: oauth2
